// ─── DAILY 日常生活 d051-d100 ─────────────────────────────
{id:'d051',dim:'daily',level:1,word:'snack',phonetic:'/snæk/',zh:'零食/小吃',example:'She grabbed a snack before the meeting.',exZh:'她在会议前拿了点零食。'},
{id:'d052',dim:'daily',level:1,word:'trash',phonetic:'/træʃ/',zh:'垃圾',example:'Please take out the trash tonight.',exZh:'请今晚把垃圾拿出去。'},
{id:'d053',dim:'daily',level:1,word:'kettle',phonetic:'/ˈkɛtəl/',zh:'水壶',example:'The kettle clicked off when the water boiled.',exZh:'水烧开后水壶自动断电了。'},
{id:'d054',dim:'daily',level:1,word:'top-up',phonetic:'/ˈtɒp ʌp/',zh:'充值/补充',example:'She topped up her transit card every Monday.',exZh:'她每周一给交通卡充值。'},
{id:'d055',dim:'daily',level:1,word:'towel',phonetic:'/ˈtaʊəl/',zh:'毛巾',example:'She hung the towel on the rack.',exZh:'她把毛巾挂在架子上。'},
{id:'d056',dim:'daily',level:1,word:'pillow',phonetic:'/ˈpɪloʊ/',zh:'枕头',example:'He bought a new pillow for better sleep.',exZh:'他买了一个新枕头以便睡得更好。'},
{id:'d057',dim:'daily',level:2,word:'leftover',phonetic:'/ˈlɛftoʊvər/',zh:'剩菜/剩余物',example:'They ate leftovers for lunch the next day.',exZh:'他们第二天午饭吃了剩菜。'},
{id:'d058',dim:'daily',level:2,word:'cupboard',phonetic:'/ˈkʌbərd/',zh:'橱柜',example:'The mugs are in the cupboard above the sink.',exZh:'杯子在水槽上方的橱柜里。'},
{id:'d059',dim:'daily',level:2,word:'detergent',phonetic:'/dɪˈtɜːrdʒənt/',zh:'洗涤剂',example:'Add detergent before starting the washing machine.',exZh:'启动洗衣机前先加洗涤剂。'},
{id:'d060',dim:'daily',level:2,word:'grocery store',phonetic:'/ˈɡroʊsəri stɔːr/',zh:'杂货店',example:'The grocery store near us is open until midnight.',exZh:'我们附近的杂货店营业到午夜。'},
{id:'d061',dim:'daily',level:2,word:'socket',phonetic:'/ˈsɒkɪt/',zh:'插座',example:'The socket by the desk stopped working.',exZh:'桌子旁边的插座不好用了。'},
{id:'d062',dim:'daily',level:2,word:'bin',phonetic:'/bɪn/',zh:'垃圾桶/收纳箱',example:'She put the empty bottle in the recycling bin.',exZh:'她把空瓶子放进了回收桶。'},
{id:'d063',dim:'daily',level:2,word:'shortcut',phonetic:'/ˈʃɔːrtkʌt/',zh:'捷径/快捷方式',example:'She found a shortcut through the park.',exZh:'她找到了一条穿过公园的捷径。'},
{id:'d064',dim:'daily',level:2,word:'shelf',phonetic:'/ʃɛlf/',zh:'架子/搁板',example:'The books are on the top shelf.',exZh:'书放在最上面的架子上。'},
{id:'d065',dim:'daily',level:3,word:'landlord',phonetic:'/ˈlændlɔːrd/',zh:'房东',example:'The landlord raised the rent by ten percent.',exZh:'房东把租金提高了百分之十。'},
{id:'d066',dim:'daily',level:3,word:'plumber',phonetic:'/ˈplʌmər/',zh:'水管工',example:'We called a plumber to fix the leaking pipe.',exZh:'我们叫了一个水管工来修漏水的管道。'},
{id:'d067',dim:'daily',level:3,word:'subscription',phonetic:'/səbˈskrɪpʃən/',zh:'订阅/订购',example:'She cancelled her streaming subscription.',exZh:'她取消了流媒体订阅。'},
{id:'d068',dim:'daily',level:3,word:'surplus',phonetic:'/ˈsɜːrpləs/',zh:'剩余/盈余',example:'They donated the food surplus to a shelter.',exZh:'他们把多余的食物捐给了庇护所。'},
{id:'d069',dim:'daily',level:3,word:'warranty',phonetic:'/ˈwɒrənti/',zh:'保修/质保',example:'The fridge comes with a two-year warranty.',exZh:'这台冰箱附带两年质保。'},
{id:'d070',dim:'daily',level:3,word:'takeaway',phonetic:'/ˈteɪkəweɪ/',zh:'外卖/带走',example:'They ordered a takeaway instead of cooking.',exZh:'他们点了外卖而不是自己做饭。'},
{id:'d071',dim:'daily',level:3,word:'passer-by',phonetic:'/ˈpɑːsər baɪ/',zh:'路人/过路人',example:'A passer-by helped her pick up the groceries.',exZh:'一位路人帮她捡起了掉落的食材。'},
{id:'d072',dim:'daily',level:3,word:'carpool',phonetic:'/ˈkɑːrpuːl/',zh:'拼车',example:'They carpool to save on petrol costs.',exZh:'他们拼车以节省油费。'},
{id:'d073',dim:'daily',level:3,word:'deposit',phonetic:'/dɪˈpɒzɪt/',zh:'押金/定金',example:'They paid a month\'s deposit before moving in.',exZh:'他们在入住前支付了一个月的押金。'},
{id:'d074',dim:'daily',level:3,word:'roster',phonetic:'/ˈrɒstər/',zh:'值班表/排班',example:'Check the roster to see your shift this week.',exZh:'查看排班表确认本周你的班次。'},
{id:'d075',dim:'daily',level:4,word:'refurbish',phonetic:'/riːˈfɜːrbɪʃ/',zh:'翻新整修',example:'The café was refurbished over the summer.',exZh:'咖啡馆在夏天进行了翻新整修。'},
{id:'d076',dim:'daily',level:4,word:'expenditure',phonetic:'/ɪkˈspɛndɪtʃər/',zh:'支出/花费',example:'Monthly expenditure exceeded their income.',exZh:'每月支出超过了他们的收入。'},
{id:'d077',dim:'daily',level:4,word:'concession',phonetic:'/kənˈsɛʃən/',zh:'优惠/折扣票',example:'Students get a concession on public transport.',exZh:'学生乘坐公共交通可享受优惠。'},
{id:'d078',dim:'daily',level:4,word:'purge',phonetic:'/pɜːrdʒ/',zh:'清理/清除',example:'She purged her wardrobe of clothes she never wore.',exZh:'她把衣橱里从不穿的衣服全部清理掉了。'},
{id:'d079',dim:'daily',level:4,word:'inventory',phonetic:'/ˈɪnvəntɔːri/',zh:'库存清单',example:'She did a full inventory of the kitchen supplies.',exZh:'她对厨房用品做了全面盘点。'},
{id:'d080',dim:'daily',level:4,word:'instalment',phonetic:'/ɪnˈstɔːlmənt/',zh:'分期付款',example:'They paid for the sofa in monthly instalments.',exZh:'他们按月分期付款买了沙发。'},
{id:'d081',dim:'daily',level:4,word:'perishable',phonetic:'/ˈpɛrɪʃəbəl/',zh:'易腐烂的',example:'Perishable items should be refrigerated.',exZh:'易腐食品应冷藏保存。'},
{id:'d082',dim:'daily',level:4,word:'remit',phonetic:'/rɪˈmɪt/',zh:'汇款/职责范围',example:'He remits money to his family every month.',exZh:'他每月给家人汇钱。'},
{id:'d083',dim:'daily',level:4,word:'lapse',phonetic:'/læps/',zh:'疏忽/间断',example:'A lapse in concentration caused the error.',exZh:'一时注意力不集中导致了失误。'},
{id:'d084',dim:'daily',level:4,word:'squalor',phonetic:'/ˈskwɒlər/',zh:'肮脏/恶劣环境',example:'The abandoned flat was in complete squalor.',exZh:'废弃的公寓里一片肮脏。'},
{id:'d085',dim:'daily',level:5,word:'dilapidated',phonetic:'/dɪˈlæpɪdeɪtɪd/',zh:'破旧不堪的',example:'The dilapidated building was finally torn down.',exZh:'这栋破旧不堪的建筑终于被拆除了。'},
{id:'d086',dim:'daily',level:5,word:'spartan',phonetic:'/ˈspɑːrtən/',zh:'简朴的/斯巴达式的',example:'His flat was spartan but clean.',exZh:'他的公寓简朴但干净。'},
{id:'d087',dim:'daily',level:5,word:'vicarious',phonetic:'/vɪˈkɛəriəs/',zh:'间接体验的',example:'She got vicarious pleasure from her friend\'s travels.',exZh:'她从朋友的旅行中获得了间接的快乐。'},
{id:'d088',dim:'daily',level:5,word:'stolid',phonetic:'/ˈstɒlɪd/',zh:'沉着镇定的',example:'He remained stolid through the morning chaos.',exZh:'他在早晨的混乱中依然沉着镇定。'},
{id:'d089',dim:'daily',level:5,word:'nominal',phonetic:'/ˈnɒmɪnəl/',zh:'名义上的/象征性的',example:'There is a nominal fee for the service.',exZh:'该服务收取象征性的费用。'},
{id:'d090',dim:'daily',level:5,word:'rectify',phonetic:'/ˈrɛktɪfaɪ/',zh:'纠正/整改',example:'The billing error was quickly rectified.',exZh:'账单错误被迅速纠正了。'},
{id:'d091',dim:'daily',level:3,word:'fixtures',phonetic:'/ˈfɪkstʃərz/',zh:'固定装置/固定设备',example:'The fixtures in the bathroom need replacing.',exZh:'浴室里的固定装置需要更换了。'},
{id:'d092',dim:'daily',level:3,word:'meter',phonetic:'/ˈmiːtər/',zh:'计量表/仪表',example:'The gas meter is read once a month.',exZh:'燃气表每月读取一次。'},
{id:'d093',dim:'daily',level:2,word:'drawer',phonetic:'/drɔːr/',zh:'抽屉',example:'The scissors are in the top drawer.',exZh:'剪刀在最上面的抽屉里。'},
{id:'d094',dim:'daily',level:2,word:'fridge',phonetic:'/frɪdʒ/',zh:'冰箱',example:'The fridge is almost empty — time to shop.',exZh:'冰箱快空了，该去购物了。'},
{id:'d095',dim:'daily',level:3,word:'downsize',phonetic:'/ˈdaʊnsaɪz/',zh:'缩减/搬小房',example:'After retirement they decided to downsize.',exZh:'退休后他们决定搬到更小的房子。'},
{id:'d096',dim:'daily',level:4,word:'amenities',phonetic:'/əˈmiːnɪtiz/',zh:'生活设施',example:'The building has excellent amenities.',exZh:'这栋大楼有优良的生活设施。'},
{id:'d097',dim:'daily',level:4,word:'overhaul',phonetic:'/ˈoʊvərˌhɔːl/',zh:'全面检修/彻底改革',example:'The kitchen needs a complete overhaul.',exZh:'厨房需要全面翻修。'},
{id:'d098',dim:'daily',level:5,word:'contingency fund',phonetic:'/kənˈtɪndʒənsi fʌnd/',zh:'应急基金',example:'Keep a contingency fund for unexpected costs.',exZh:'留一笔应急基金以备意外开销。'},
{id:'d099',dim:'daily',level:5,word:'superfluous',phonetic:'/suːˈpɜːrfluəs/',zh:'多余的/不必要的',example:'Remove any superfluous items from the shelf.',exZh:'把架子上多余的东西清走。'},
{id:'d100',dim:'daily',level:6,word:'penury',phonetic:'/ˈpɛnjʊri/',zh:'极度贫困',example:'They lived in penury for most of their lives.',exZh:'他们大半辈子都生活在极度贫困中。'},

// ─── EMOTION 情感心理 e051-e100 ──────────────────────────
{id:'e051',dim:'emotion',level:1,word:'proud',phonetic:'/praʊd/',zh:'自豪的',example:'She felt proud after finishing the race.',exZh:'完成比赛后她感到十分自豪。'},
{id:'e052',dim:'emotion',level:1,word:'curious',phonetic:'/ˈkjʊəriəs/',zh:'好奇的',example:'The child was curious about everything.',exZh:'这个孩子对一切都充满好奇。'},
{id:'e053',dim:'emotion',level:1,word:'calm',phonetic:'/kɑːm/',zh:'平静的',example:'She stayed calm during the emergency.',exZh:'紧急情况下她保持了平静。'},
{id:'e054',dim:'emotion',level:1,word:'hopeless',phonetic:'/ˈhoʊpləs/',zh:'绝望的',example:'He felt hopeless after losing the job.',exZh:'失业后他感到十分绝望。'},
{id:'e055',dim:'emotion',level:2,word:'irritated',phonetic:'/ˈɪrɪteɪtɪd/',zh:'恼火的',example:'She was irritated by the constant noise.',exZh:'持续的噪音让她十分恼火。'},
{id:'e056',dim:'emotion',level:2,word:'thrilled',phonetic:'/θrɪld/',zh:'激动万分的',example:'He was thrilled to receive the acceptance letter.',exZh:'收到录取通知书时他激动万分。'},
{id:'e057',dim:'emotion',level:2,word:'drained',phonetic:'/dreɪnd/',zh:'精疲力竭的',example:'She felt emotionally drained after the argument.',exZh:'争吵过后她感到精疲力竭。'},
{id:'e058',dim:'emotion',level:2,word:'restless',phonetic:'/ˈrɛstləs/',zh:'坐立不安的',example:'He was restless the night before the exam.',exZh:'考试前一晚他坐立不安。'},
{id:'e059',dim:'emotion',level:2,word:'offended',phonetic:'/əˈfɛndɪd/',zh:'被冒犯的',example:'She was offended by the careless remark.',exZh:'那句不经心的话让她感到被冒犯了。'},
{id:'e060',dim:'emotion',level:2,word:'moved',phonetic:'/muːvd/',zh:'感动的',example:'The speech moved everyone in the room.',exZh:'那篇演讲感动了在场的每一个人。'},
{id:'e061',dim:'emotion',level:3,word:'resigned',phonetic:'/rɪˈzaɪnd/',zh:'听天由命的',example:'He had a resigned look on his face.',exZh:'他脸上带着一副听天由命的表情。'},
{id:'e062',dim:'emotion',level:3,word:'appalled',phonetic:'/əˈpɔːld/',zh:'震惊愤慨的',example:'She was appalled by the living conditions.',exZh:'那里的生活条件让她震惊愤慨。'},
{id:'e063',dim:'emotion',level:3,word:'yearning',phonetic:'/ˈjɜːrnɪŋ/',zh:'渴望/思念',example:'He felt a deep yearning for home.',exZh:'他心中充满了对家的深切思念。'},
{id:'e064',dim:'emotion',level:3,word:'flustered',phonetic:'/ˈflʌstərd/',zh:'慌乱的',example:'She got flustered when asked unexpectedly.',exZh:'被突然提问时她慌乱起来。'},
{id:'e065',dim:'emotion',level:3,word:'deflated',phonetic:'/dɪˈfleɪtɪd/',zh:'沮丧泄气的',example:'He felt deflated after the rejection.',exZh:'被拒绝后他感到十分沮丧。'},
{id:'e066',dim:'emotion',level:3,word:'smug',phonetic:'/smʌɡ/',zh:'自鸣得意的',example:'Her smug smile annoyed everyone.',exZh:'她自鸣得意的笑容让所有人烦透了。'},
{id:'e067',dim:'emotion',level:3,word:'pensive',phonetic:'/ˈpɛnsɪv/',zh:'沉思的',example:'He sat by the window in a pensive mood.',exZh:'他沉思着坐在窗边。'},
{id:'e068',dim:'emotion',level:4,word:'disenchanted',phonetic:'/ˌdɪsɪnˈtʃæntɪd/',zh:'幻想破灭的',example:'She became disenchanted with city life.',exZh:'她对城市生活感到幻想破灭。'},
{id:'e069',dim:'emotion',level:4,word:'euphoric',phonetic:'/juːˈfɒrɪk/',zh:'欣喜若狂的',example:'He was euphoric when they won the championship.',exZh:'他们赢得冠军时他欣喜若狂。'},
{id:'e070',dim:'emotion',level:4,word:'apprehension',phonetic:'/ˌæprɪˈhɛnʃən/',zh:'忧虑/担心',example:'She had a sense of apprehension before surgery.',exZh:'手术前她心怀忧虑。'},
{id:'e071',dim:'emotion',level:4,word:'trepidation',phonetic:'/ˌtrɛpɪˈdeɪʃən/',zh:'惶恐不安',example:'He opened the letter with trepidation.',exZh:'他惶恐不安地拆开了那封信。'},
{id:'e072',dim:'emotion',level:4,word:'incredulous',phonetic:'/ɪnˈkrɛdjʊləs/',zh:'难以置信的',example:'She was incredulous at the sudden news.',exZh:'她对这突如其来的消息难以置信。'},
{id:'e073',dim:'emotion',level:4,word:'mortified',phonetic:'/ˈmɔːrtɪfaɪd/',zh:'极度羞愧的',example:'He was mortified when he forgot her name.',exZh:'他忘了她的名字，感到极度羞愧。'},
{id:'e074',dim:'emotion',level:4,word:'blasé',phonetic:'/ˈblɑːzeɪ/',zh:'漠然无感的',example:'She seemed blasé about her own success.',exZh:'她对自己的成功似乎漠然无感。'},
{id:'e075',dim:'emotion',level:5,word:'lugubrious',phonetic:'/luːˈɡuːbriəs/',zh:'忧郁悲戚的',example:'His lugubrious expression silenced the room.',exZh:'他忧郁悲戚的表情让整个房间沉默了。'},
{id:'e076',dim:'emotion',level:5,word:'ebullience',phonetic:'/ɪˈbʊliəns/',zh:'热情洋溢',example:'Her ebullience lit up every room she entered.',exZh:'她的热情洋溢照亮了每一个她走进的房间。'},
{id:'e077',dim:'emotion',level:5,word:'languor',phonetic:'/ˈlæŋɡər/',zh:'慵懒倦怠',example:'A pleasant languor washed over her after lunch.',exZh:'午饭后一股惬意的慵懒倦怠感涌上心头。'},
{id:'e078',dim:'emotion',level:5,word:'lassitude',phonetic:'/ˈlæsɪtjuːd/',zh:'疲倦/无精打采',example:'A deep lassitude settled over him after the journey.',exZh:'旅途结束后他陷入了深深的疲倦。'},
{id:'e079',dim:'emotion',level:5,word:'propriety',phonetic:'/prəˈpraɪɪti/',zh:'得体/合宜',example:'She maintained propriety even under provocation.',exZh:'即使受到挑衅她也保持了得体的举止。'},
{id:'e080',dim:'emotion',level:5,word:'acrimony',phonetic:'/ˈækrɪməni/',zh:'尖刻/激烈',example:'The divorce was filled with acrimony.',exZh:'这场离婚充满了激烈的争执。'},
{id:'e081',dim:'emotion',level:3,word:'unsettled',phonetic:'/ʌnˈsɛtəld/',zh:'心神不宁的',example:'The news left her feeling unsettled all day.',exZh:'那个消息让她一整天都心神不宁。'},
{id:'e082',dim:'emotion',level:3,word:'bitter',phonetic:'/ˈbɪtər/',zh:'痛苦的/怨恨的',example:'He grew bitter after years of disappointment.',exZh:'多年失望让他心生怨恨。'},
{id:'e083',dim:'emotion',level:2,word:'reassured',phonetic:'/ˌriːəˈʃʊərd/',zh:'放心的/被安慰的',example:'She felt reassured after talking to the doctor.',exZh:'和医生谈过之后她放心多了。'},
{id:'e084',dim:'emotion',level:4,word:'disquiet',phonetic:'/dɪsˈkwaɪɪt/',zh:'不安/焦虑',example:'A sense of disquiet followed her home.',exZh:'一种不安感一路伴随她回到家。'},
{id:'e085',dim:'emotion',level:4,word:'elation',phonetic:'/ɪˈleɪʃən/',zh:'喜悦/欢欣',example:'The elation of victory quickly faded.',exZh:'胜利的喜悦很快消散了。'},
{id:'e086',dim:'emotion',level:5,word:'rancour',phonetic:'/ˈræŋkər/',zh:'积怨/深仇',example:'Years of rancour poisoned their relationship.',exZh:'多年的积怨毒化了他们的关系。'},
{id:'e087',dim:'emotion',level:5,word:'agitation',phonetic:'/ˌædʒɪˈteɪʃən/',zh:'激动/焦虑不安',example:'His agitation was visible throughout the meeting.',exZh:'他在整个会议中都明显表现出焦虑不安。'},
{id:'e088',dim:'emotion',level:6,word:'weltschmerz',phonetic:'/ˈvɛltʃmɛrts/',zh:'世界之痛/悲世情绪',example:'A sense of weltschmerz gripped him in his twenties.',exZh:'二十几岁时一股悲世情绪笼罩了他。'},
{id:'e089',dim:'emotion',level:6,word:'hiraeth',phonetic:'/ˈhɪraɪθ/',zh:'对故乡的深切思念',example:'The melody stirred an old sense of hiraeth.',exZh:'那段旋律勾起了他对故乡的深切思念。'},
{id:'e090',dim:'emotion',level:3,word:'sheepish',phonetic:'/ˈʃiːpɪʃ/',zh:'局促不安的/惭愧的',example:'He gave a sheepish grin after the mistake.',exZh:'犯错后他不好意思地咧嘴一笑。'},
{id:'e091',dim:'emotion',level:3,word:'fretful',phonetic:'/ˈfrɛtfʊl/',zh:'烦躁不安的',example:'The long wait made her fretful.',exZh:'漫长的等待让她烦躁不安。'},
{id:'e092',dim:'emotion',level:4,word:'wary',phonetic:'/ˈwɛri/',zh:'警惕的',example:'She was wary of trusting strangers.',exZh:'她对信任陌生人保持警惕。'},
{id:'e093',dim:'emotion',level:4,word:'placid',phonetic:'/ˈplæsɪd/',zh:'平和宁静的',example:'He had a placid temperament that calmed others.',exZh:'他平和的性情能让周围的人平静下来。'},
{id:'e094',dim:'emotion',level:5,word:'diffidence',phonetic:'/ˈdɪfɪdəns/',zh:'缺乏自信/羞怯',example:'Her diffidence prevented her from speaking up.',exZh:'缺乏自信使她无法大声说出来。'},
{id:'e095',dim:'emotion',level:5,word:'ardour',phonetic:'/ˈɑːrdər/',zh:'热忱/热情',example:'He pursued the project with great ardour.',exZh:'他以极大的热忱投入到这个项目中。'},
{id:'e096',dim:'emotion',level:6,word:'dysphoria',phonetic:'/dɪsˈfɔːriə/',zh:'烦躁不快',example:'A persistent dysphoria clouded her mood.',exZh:'持续的烦躁不快笼罩着她的心情。'},
{id:'e097',dim:'emotion',level:3,word:'startled',phonetic:'/ˈstɑːrtəld/',zh:'受惊的',example:'She was startled by the sudden sound.',exZh:'她被突然的声音吓了一跳。'},
{id:'e098',dim:'emotion',level:2,word:'cheerful',phonetic:'/ˈtʃɪərfʊl/',zh:'愉快的',example:'He was always cheerful in the mornings.',exZh:'他早上总是精神愉快。'},
{id:'e099',dim:'emotion',level:4,word:'turbulent',phonetic:'/ˈtɜːrbjʊlənt/',zh:'动荡的/情绪激烈的',example:'It was a turbulent period in her life.',exZh:'那是她人生中动荡的一段时期。'},
{id:'e100',dim:'emotion',level:6,word:'numinous',phonetic:'/ˈnjuːmɪnəs/',zh:'神圣神秘的感召',example:'The cathedral had a numinous quality.',exZh:'这座大教堂带有一种神圣神秘的气质。'},

// ─── ABSTRACT 抽象概念 a051-a100 ─────────────────────────
{id:'a051',dim:'abstract',level:1,word:'purpose',phonetic:'/ˈpɜːrpəs/',zh:'目的/使命感',example:'She found her purpose in teaching.',exZh:'她在教学中找到了自己的使命感。'},
{id:'a052',dim:'abstract',level:1,word:'belief',phonetic:'/bɪˈliːf/',zh:'信念',example:'His belief in fairness never wavered.',exZh:'他对公平的信念从未动摇。'},
{id:'a053',dim:'abstract',level:2,word:'duality',phonetic:'/djuːˈælɪti/',zh:'二元性/双重性',example:'The duality of human nature is a classic theme.',exZh:'人性的双重性是一个经典主题。'},
{id:'a054',dim:'abstract',level:2,word:'coherence',phonetic:'/koʊˈhɪərəns/',zh:'连贯性/一致性',example:'The plan lacked coherence.',exZh:'这个计划缺乏连贯性。'},
{id:'a055',dim:'abstract',level:2,word:'illusion',phonetic:'/ɪˈluːʒən/',zh:'幻觉/错觉',example:'Success can be an illusion.',exZh:'成功有时可以是一种幻觉。'},
{id:'a056',dim:'abstract',level:2,word:'theory',phonetic:'/ˈθɪəri/',zh:'理论',example:'His theory was widely debated.',exZh:'他的理论被广泛讨论。'},
{id:'a057',dim:'abstract',level:3,word:'deduction',phonetic:'/dɪˈdʌkʃən/',zh:'演绎/推论',example:'Her conclusion was based on careful deduction.',exZh:'她的结论基于谨慎的演绎推理。'},
{id:'a058',dim:'abstract',level:3,word:'threshold',phonetic:'/ˈθrɛʃhoʊld/',zh:'临界点/门槛',example:'Pain has a different threshold for everyone.',exZh:'每个人对疼痛的临界点不同。'},
{id:'a059',dim:'abstract',level:3,word:'virtue',phonetic:'/ˈvɜːrtʃuː/',zh:'美德',example:'Patience is considered a great virtue.',exZh:'耐心被视为一种重要美德。'},
{id:'a060',dim:'abstract',level:3,word:'fallacy',phonetic:'/ˈfæləsi/',zh:'谬论/错误推理',example:'His argument was built on a fundamental fallacy.',exZh:'他的论点建立在一个根本性谬论之上。'},
{id:'a061',dim:'abstract',level:3,word:'perception',phonetic:'/pərˈsɛpʃən/',zh:'感知/看法',example:'Perception shapes how we experience reality.',exZh:'感知塑造了我们体验现实的方式。'},
{id:'a062',dim:'abstract',level:3,word:'spectrum',phonetic:'/ˈspɛktrəm/',zh:'光谱/范围',example:'Opinions exist across a wide spectrum.',exZh:'观点存在于广泛的范围之中。'},
{id:'a063',dim:'abstract',level:3,word:'catalyst',phonetic:'/ˈkætəlɪst/',zh:'催化剂/导火索',example:'The speech acted as a catalyst for change.',exZh:'那篇演讲成为变革的催化剂。'},
{id:'a064',dim:'abstract',level:4,word:'fallibilism',phonetic:'/ˈfælɪbɪlɪzəm/',zh:'可错论',example:'Fallibilism holds that knowledge can be revised.',exZh:'可错论认为知识是可以被修正的。'},
{id:'a065',dim:'abstract',level:4,word:'axiom',phonetic:'/ˈæksiəm/',zh:'公理/不言而喻的原则',example:'Equality is treated as an axiom in modern law.',exZh:'平等在现代法律中被视为一条公理。'},
{id:'a066',dim:'abstract',level:4,word:'integration',phonetic:'/ˌɪntɪˈɡreɪʃən/',zh:'整合/融合',example:'Integration of ideas is central to philosophy.',exZh:'观念的整合是哲学的核心。'},
{id:'a067',dim:'abstract',level:4,word:'notion',phonetic:'/ˈnoʊʃən/',zh:'观念/概念',example:'The notion of fairness differs by culture.',exZh:'公平的观念因文化而异。'},
{id:'a068',dim:'abstract',level:4,word:'symmetry',phonetic:'/ˈsɪmɪtri/',zh:'对称/均衡',example:'There is beauty in symmetry.',exZh:'对称之中存在美。'},
{id:'a069',dim:'abstract',level:4,word:'magnitude',phonetic:'/ˈmæɡnɪtjuːd/',zh:'规模/重要性',example:'The magnitude of the problem was underestimated.',exZh:'问题的规模被低估了。'},
{id:'a070',dim:'abstract',level:4,word:'flux',phonetic:'/flʌks/',zh:'不断变化/流动状态',example:'Society is in a constant state of flux.',exZh:'社会处于不断变化的状态中。'},
{id:'a071',dim:'abstract',level:4,word:'agency',phonetic:'/ˈeɪdʒənsi/',zh:'主动性/能动性',example:'People need a sense of agency over their lives.',exZh:'人们需要对自己的生活拥有能动性。'},
{id:'a072',dim:'abstract',level:5,word:'veracity',phonetic:'/vəˈræsɪti/',zh:'真实性/诚实',example:'The veracity of the report was questioned.',exZh:'报告的真实性受到了质疑。'},
{id:'a073',dim:'abstract',level:5,word:'contingency',phonetic:'/kənˈtɪndʒənsi/',zh:'偶然性/不确定事件',example:'All plans must account for contingency.',exZh:'所有计划都必须考虑到偶然性。'},
{id:'a074',dim:'abstract',level:5,word:'reification',phonetic:'/ˌreɪɪfɪˈkeɪʃən/',zh:'具象化/物化',example:'Reification treats abstract ideas as concrete things.',exZh:'物化是将抽象概念当作具体事物来对待。'},
{id:'a075',dim:'abstract',level:5,word:'praxis',phonetic:'/ˈpræksɪs/',zh:'实践/实践活动',example:'Theory without praxis remains incomplete.',exZh:'没有实践的理论是不完整的。'},
{id:'a076',dim:'abstract',level:5,word:'cogency',phonetic:'/ˈkoʊdʒənsi/',zh:'说服力/逻辑力',example:'The argument\'s cogency convinced the panel.',exZh:'论证的说服力打动了评审团。'},
{id:'a077',dim:'abstract',level:5,word:'verisimilitude',phonetic:'/ˌvɛrɪsɪˈmɪlɪtjuːd/',zh:'逼真感/似真性',example:'A good novel requires a degree of verisimilitude.',exZh:'好的小说需要一定程度的逼真感。'},
{id:'a078',dim:'abstract',level:6,word:'noumenon',phonetic:'/ˈnuːmɪnɒn/',zh:'本体/物自身(康德)',example:'Kant distinguished phenomena from noumena.',exZh:'康德区分了现象与物自身。'},
{id:'a079',dim:'abstract',level:6,word:'intersubjectivity',phonetic:'/ˌɪntərsəbˌdʒɛktɪˈvɪti/',zh:'主体间性',example:'Language depends on intersubjectivity.',exZh:'语言依赖于主体间性。'},
{id:'a080',dim:'abstract',level:6,word:'aphorism',phonetic:'/ˈæfərɪzəm/',zh:'格言/警句',example:'The book is full of memorable aphorisms.',exZh:'这本书充满了令人难忘的格言。'},
{id:'a081',dim:'abstract',level:3,word:'purview',phonetic:'/ˈpɜːrvjuː/',zh:'范围/职权范围',example:'That question falls outside the purview of this study.',exZh:'那个问题超出了本研究的范围。'},
{id:'a082',dim:'abstract',level:3,word:'supposition',phonetic:'/ˌsʌpəˈzɪʃən/',zh:'假设/猜测',example:'The theory rests on a supposition that needs testing.',exZh:'这个理论建立在一个需要检验的假设之上。'},
{id:'a083',dim:'abstract',level:2,word:'norm',phonetic:'/nɔːrm/',zh:'规范/常态',example:'It became the norm to work from home.',exZh:'居家办公成了常态。'},
{id:'a084',dim:'abstract',level:3,word:'premise',phonetic:'/ˈprɛmɪs/',zh:'前提',example:'The argument rests on a flawed premise.',exZh:'这个论点建立在一个有缺陷的前提上。'},
{id:'a085',dim:'abstract',level:4,word:'asymmetry',phonetic:'/eɪˈsɪmɪtri/',zh:'不对称',example:'There is a power asymmetry in the relationship.',exZh:'这段关系中存在权力不对称。'},
{id:'a086',dim:'abstract',level:4,word:'empiricism',phonetic:'/ɪmˈpɪrɪsɪzəm/',zh:'经验主义',example:'Empiricism values observation over pure reason.',exZh:'经验主义重视观察而非纯粹推理。'},
{id:'a087',dim:'abstract',level:5,word:'nominalism',phonetic:'/ˈnɒmɪnəlɪzəm/',zh:'唯名论',example:'Nominalism denies that abstract objects exist.',exZh:'唯名论否认抽象对象的存在。'},
{id:'a088',dim:'abstract',level:5,word:'perspectivism',phonetic:'/pərˈspɛktɪvɪzəm/',zh:'透视主义',example:'Nietzsche\'s perspectivism holds there are no facts, only interpretations.',exZh:'尼采的透视主义认为没有事实，只有诠释。'},
{id:'a089',dim:'abstract',level:6,word:'apperception',phonetic:'/ˌæpəˈsɛpʃən/',zh:'统觉/自我意识',example:'Apperception is the mind\'s awareness of itself.',exZh:'统觉是心灵对自身的意识。'},
{id:'a090',dim:'abstract',level:6,word:'sui generis',phonetic:'/ˌsuːi ˈdʒɛnərɪs/',zh:'独一无二的',example:'Her style was truly sui generis.',exZh:'她的风格是真正独一无二的。'},
{id:'a091',dim:'abstract',level:2,word:'constraint',phonetic:'/kənˈstreɪnt/',zh:'约束/限制',example:'Budget constraints limited their choices.',exZh:'预算约束限制了他们的选择。'},
{id:'a092',dim:'abstract',level:3,word:'equilibrium',phonetic:'/ˌiːkwɪˈlɪbriəm/',zh:'平衡/均衡',example:'They struggled to find equilibrium after the shock.',exZh:'他们在冲击后努力寻求平衡。'},
{id:'a093',dim:'abstract',level:4,word:'determinacy',phonetic:'/dɪˈtɜːrmɪnəsi/',zh:'确定性',example:'Lack of determinacy made planning hard.',exZh:'缺乏确定性使规划变得困难。'},
{id:'a094',dim:'abstract',level:4,word:'conjecture',phonetic:'/kənˈdʒɛktʃər/',zh:'推测/猜想',example:'The theory remained conjecture without evidence.',exZh:'缺乏证据，该理论仍只是推测。'},
{id:'a095',dim:'abstract',level:5,word:'sublimation',phonetic:'/ˌsʌblɪˈmeɪʃən/',zh:'升华/转化',example:'Art can be a sublimation of pain.',exZh:'艺术可以是痛苦的升华。'},
{id:'a096',dim:'abstract',level:5,word:'negation',phonetic:'/nɪˈɡeɪʃən/',zh:'否定/否认',example:'The negation of one idea often births another.',exZh:'对一种观念的否定往往孕育出另一种观念。'},
{id:'a097',dim:'abstract',level:6,word:'ineffability',phonetic:'/ɪnˌɛfəˈbɪlɪti/',zh:'不可言说性',example:'Mystics often speak of the ineffability of God.',exZh:'神秘主义者常谈论神的不可言说性。'},
{id:'a098',dim:'abstract',level:3,word:'convention',phonetic:'/kənˈvɛnʃən/',zh:'惯例/约定俗成',example:'Breaking convention takes courage.',exZh:'打破惯例需要勇气。'},
{id:'a099',dim:'abstract',level:4,word:'mediation',phonetic:'/ˌmiːdiˈeɪʃən/',zh:'中介/调解',example:'Language is a mediation between thought and reality.',exZh:'语言是思想与现实之间的中介。'},
{id:'a100',dim:'abstract',level:5,word:'immanence',phonetic:'/ˈɪmənəns/',zh:'内在性',example:'Spinoza believed in God\'s immanence in all things.',exZh:'斯宾诺莎相信神内在于万物之中。'},

// ─── SOCIAL 社交场景 s051-s100 ────────────────────────────
{id:'s051',dim:'social',level:1,word:'mingle',phonetic:'/ˈmɪŋɡəl/',zh:'混在一起/交际',example:'She loves to mingle at parties.',exZh:'她喜欢在派对上与人交际。'},
{id:'s052',dim:'social',level:1,word:'favour',phonetic:'/ˈfeɪvər/',zh:'帮忙/人情',example:'Could you do me a favour?',exZh:'你能帮我一个忙吗？'},
{id:'s053',dim:'social',level:1,word:'chat',phonetic:'/tʃæt/',zh:'闲聊',example:'We had a quick chat over coffee.',exZh:'我们喝咖啡时聊了一会儿。'},
{id:'s054',dim:'social',level:2,word:'small talk',phonetic:'/smɔːl tɔːk/',zh:'闲谈/寒暄',example:'Small talk is essential at networking events.',exZh:'寒暄在社交活动中必不可少。'},
{id:'s055',dim:'social',level:2,word:'bond',phonetic:'/bɒnd/',zh:'纽带/联系',example:'They formed a strong bond during training.',exZh:'他们在培训期间建立了深厚的联系。'},
{id:'s056',dim:'social',level:2,word:'goodwill',phonetic:'/ˌɡʊdˈwɪl/',zh:'善意/友好',example:'The gesture was an act of genuine goodwill.',exZh:'那个举动是真诚善意的表示。'},
{id:'s057',dim:'social',level:2,word:'tact',phonetic:'/tækt/',zh:'机智/圆通',example:'She handled the disagreement with great tact.',exZh:'她以极大的机智化解了分歧。'},
{id:'s058',dim:'social',level:2,word:'assertive',phonetic:'/əˈsɜːrtɪv/',zh:'自信果断的',example:'Being assertive helps in professional settings.',exZh:'自信果断在职业环境中很有帮助。'},
{id:'s059',dim:'social',level:2,word:'outgoing',phonetic:'/ˈaʊtɡoʊɪŋ/',zh:'外向的',example:'Her outgoing nature helped her make friends quickly.',exZh:'她外向的性格让她很快交到了朋友。'},
{id:'s060',dim:'social',level:3,word:'candid',phonetic:'/ˈkændɪd/',zh:'坦率的',example:'He was candid about his mistakes.',exZh:'他坦率地承认了自己的错误。'},
{id:'s061',dim:'social',level:3,word:'overture',phonetic:'/ˈoʊvərtʃər/',zh:'主动示好/序幕',example:'She made the first overture of friendship.',exZh:'她率先主动示好，表达友谊。'},
{id:'s062',dim:'social',level:3,word:'reconcile',phonetic:'/ˈrɛkənsaɪl/',zh:'和解',example:'They reconciled after a long estrangement.',exZh:'他们在长期疏远后重归于好。'},
{id:'s063',dim:'social',level:3,word:'snub',phonetic:'/snʌb/',zh:'冷落/怠慢',example:'She felt snubbed when no one greeted her.',exZh:'没有人打招呼，她感到被冷落了。'},
{id:'s064',dim:'social',level:3,word:'flattery',phonetic:'/ˈflætəri/',zh:'奉承/谄媚',example:'His flattery was so obvious it backfired.',exZh:'他的奉承太明显，适得其反。'},
{id:'s065',dim:'social',level:3,word:'civility',phonetic:'/sɪˈvɪlɪti/',zh:'礼貌/文明',example:'Even rivals can treat each other with civility.',exZh:'即使是对手也可以以礼相待。'},
{id:'s066',dim:'social',level:3,word:'affiliate',phonetic:'/əˈfɪlieɪt/',zh:'加入/隶属',example:'She affiliated with a local running club.',exZh:'她加入了当地的跑步俱乐部。'},
{id:'s067',dim:'social',level:4,word:'diffuse',phonetic:'/dɪˈfjuːz/',zh:'缓解/化解(紧张)',example:'A joke can diffuse tension in a room.',exZh:'一个笑话能化解房间里的紧张气氛。'},
{id:'s068',dim:'social',level:4,word:'leverage',phonetic:'/ˈlɛvərɪdʒ/',zh:'影响力/利用',example:'She used her network as leverage in negotiations.',exZh:'她把自己的人脉作为谈判筹码。'},
{id:'s069',dim:'social',level:4,word:'detractor',phonetic:'/dɪˈtræktər/',zh:'诋毁者/批评者',example:'Every leader has detractors.',exZh:'每位领导者都有批评者。'},
{id:'s070',dim:'social',level:4,word:'ingratiate',phonetic:'/ɪnˈɡreɪʃieɪt/',zh:'讨好/巴结',example:'He tried to ingratiate himself with the boss.',exZh:'他试图讨好老板。'},
{id:'s071',dim:'social',level:4,word:'vested interest',phonetic:'/ˌvɛstɪd ˈɪntrəst/',zh:'既得利益',example:'Those with vested interests opposed the change.',exZh:'有既得利益的人反对这一变化。'},
{id:'s072',dim:'social',level:4,word:'antagonise',phonetic:'/ænˈtæɡənaɪz/',zh:'激怒/使敌视',example:'His bluntness tends to antagonise people.',exZh:'他的直率往往会激怒别人。'},
{id:'s073',dim:'social',level:4,word:'patronage',phonetic:'/ˈpætrənɪdʒ/',zh:'赞助/庇护',example:'The event ran thanks to generous patronage.',exZh:'这次活动靠慷慨的赞助得以举办。'},
{id:'s074',dim:'social',level:5,word:'prestige',phonetic:'/prɛˈstiːʒ/',zh:'声望/威信',example:'The university enjoys great prestige.',exZh:'这所大学享有很高的声望。'},
{id:'s075',dim:'social',level:5,word:'nepotism',phonetic:'/ˈnɛpətɪzəm/',zh:'裙带关系',example:'Nepotism undermines trust in organisations.',exZh:'裙带关系损害了组织内部的信任。'},
{id:'s076',dim:'social',level:5,word:'entourage',phonetic:'/ˈɒntʊrɑːʒ/',zh:'随行人员/圈子',example:'The celebrity arrived with her entourage.',exZh:'那位名人带着她的随行人员到场。'},
{id:'s077',dim:'social',level:5,word:'polarise',phonetic:'/ˈpoʊləraɪz/',zh:'使对立/两极分化',example:'The debate polarised public opinion.',exZh:'这场辩论使公众意见两极分化。'},
{id:'s078',dim:'social',level:5,word:'tribalism',phonetic:'/ˈtraɪbəlɪzəm/',zh:'部落主义/小圈子意识',example:'Online tribalism makes nuanced debate harder.',exZh:'网络上的小圈子意识让有深度的讨论更加困难。'},
{id:'s079',dim:'social',level:6,word:'sycophancy',phonetic:'/ˈsɪkəfənsi/',zh:'谄媚奉承',example:'The court was rife with sycophancy.',exZh:'朝廷里充斥着谄媚奉承之风。'},
{id:'s080',dim:'social',level:6,word:'lèse-majesté',phonetic:'/ˌleɪz mæˈʒɛsteɪ/',zh:'冒犯尊贵/大不敬',example:'Criticising the monarch was considered lèse-majesté.',exZh:'批评君主被视为大不敬。'},
{id:'s081',dim:'social',level:2,word:'tactful',phonetic:'/ˈtæktfʊl/',zh:'得体的/有分寸的',example:'A tactful reply can avoid hurt feelings.',exZh:'得体的回复可以避免伤害感情。'},
{id:'s082',dim:'social',level:3,word:'endorse',phonetic:'/ɪnˈdɔːrs/',zh:'认可/背书',example:'She publicly endorsed the candidate.',exZh:'她公开为这位候选人背书。'},
{id:'s083',dim:'social',level:3,word:'alienate',phonetic:'/ˈeɪliəneɪt/',zh:'疏远',example:'His harsh criticism alienated his supporters.',exZh:'他严厉的批评疏远了他的支持者。'},
{id:'s084',dim:'social',level:3,word:'discourse',phonetic:'/ˈdɪskɔːrs/',zh:'话语/交流',example:'Civil discourse is essential in democracy.',exZh:'文明的交流对民主至关重要。'},
{id:'s085',dim:'social',level:4,word:'dynamics',phonetic:'/daɪˈnæmɪks/',zh:'动态关系',example:'The group dynamics shifted after she left.',exZh:'她离开后团队的动态关系发生了变化。'},
{id:'s086',dim:'social',level:4,word:'acquiesce',phonetic:'/ˌækwiˈɛs/',zh:'默然同意/顺从',example:'He acquiesced to the group\'s decision.',exZh:'他默然接受了团队的决定。'},
{id:'s087',dim:'social',level:5,word:'complicity',phonetic:'/kəmˈplɪsɪti/',zh:'共谋/同谋',example:'Silence can be a form of complicity.',exZh:'沉默有时是一种共谋。'},
{id:'s088',dim:'social',level:5,word:'conviviality',phonetic:'/kənˌvɪviˈælɪti/',zh:'欢聚的气氛/好客',example:'The dinner was marked by warmth and conviviality.',exZh:'晚宴洋溢着温暖欢聚的气氛。'},
{id:'s089',dim:'social',level:6,word:'dissimulation',phonetic:'/dɪˌsɪmjʊˈleɪʃən/',zh:'伪装/掩饰',example:'His friendliness was pure dissimulation.',exZh:'他的友好纯粹是一种伪装。'},
{id:'s090',dim:'social',level:6,word:'ignominy',phonetic:'/ˈɪɡnəmɪni/',zh:'奇耻大辱',example:'The defeat brought ignominy to the whole team.',exZh:'这场失败给整个团队带来了奇耻大辱。'},
{id:'s091',dim:'social',level:2,word:'blunt',phonetic:'/blʌnt/',zh:'直言不讳的',example:'She was blunt but never unkind.',exZh:'她直言不讳，但从不刻薄。'},
{id:'s092',dim:'social',level:3,word:'esteem',phonetic:'/ɪˈstiːm/',zh:'尊重/尊敬',example:'He was held in high esteem by his peers.',exZh:'他深受同辈的尊重。'},
{id:'s093',dim:'social',level:4,word:'faction',phonetic:'/ˈfækʃən/',zh:'派系',example:'The party split into rival factions.',exZh:'该党分裂成了互相对立的派系。'},
{id:'s094',dim:'social',level:4,word:'bargaining chip',phonetic:'/ˈbɑːrɡɪnɪŋ tʃɪp/',zh:'谈判筹码',example:'Information can be a powerful bargaining chip.',exZh:'信息可以是强有力的谈判筹码。'},
{id:'s095',dim:'social',level:5,word:'magnanimity',phonetic:'/ˌmæɡnəˈnɪmɪti/',zh:'宽宏大量',example:'She accepted the apology with magnanimity.',exZh:'她以宽宏大量接受了道歉。'},
{id:'s096',dim:'social',level:5,word:'posturing',phonetic:'/ˈpɒstʃərɪŋ/',zh:'摆姿态/作态',example:'Much of the negotiation was mere posturing.',exZh:'谈判的大部分内容不过是在摆姿态。'},
{id:'s097',dim:'social',level:6,word:'contumely',phonetic:'/ˈkɒntjʊməli/',zh:'侮辱/蔑视',example:'He endured public contumely with dignity.',exZh:'他以尊严承受了公众的侮辱。'},
{id:'s098',dim:'social',level:3,word:'common ground',phonetic:'/ˈkɒmən ɡraʊnd/',zh:'共同点/共识基础',example:'Finding common ground is the first step in any negotiation.',exZh:'找到共同点是任何谈判的第一步。'},
{id:'s099',dim:'social',level:4,word:'disarm',phonetic:'/dɪˈsɑːrm/',zh:'消除戒心/解除武装',example:'Her smile disarmed even the most hostile critics.',exZh:'她的微笑消除了连最敌对的批评者的戒心。'},
{id:'s100',dim:'social',level:5,word:'enmity',phonetic:'/ˈɛnmɪti/',zh:'敌意/仇恨',example:'Years of enmity between them finally ended.',exZh:'他们之间多年的敌意终于结束了。'},

// ─── ACADEMIC 学术书面 ac051-ac100 ──────────────────────
{id:'ac051',dim:'academic',level:1,word:'outline',phonetic:'/ˈaʊtlaɪn/',zh:'提纲/概述',example:'Write an outline before drafting the essay.',exZh:'在起草文章前先写提纲。'},
{id:'ac052',dim:'academic',level:1,word:'draft',phonetic:'/drɑːft/',zh:'草稿/起草',example:'Submit a draft by Friday for feedback.',exZh:'周五前提交草稿以获得反馈。'},
{id:'ac053',dim:'academic',level:2,word:'research scope',phonetic:'/rɪˈsɜːrtʃ skoʊp/',zh:'研究范围',example:'Define the research scope clearly at the outset.',exZh:'在一开始就清楚地界定研究范围。'},
{id:'ac054',dim:'academic',level:2,word:'findings',phonetic:'/ˈfaɪndɪŋz/',zh:'研究发现/结果',example:'The findings challenged existing assumptions.',exZh:'研究发现挑战了现有的假设。'},
{id:'ac055',dim:'academic',level:2,word:'framework',phonetic:'/ˈfreɪmwɜːrk/',zh:'框架/理论体系',example:'The study uses a constructivist framework.',exZh:'该研究采用建构主义框架。'},
{id:'ac056',dim:'academic',level:2,word:'rationale',phonetic:'/ˌræʃəˈnɑːl/',zh:'理由/依据',example:'Explain the rationale behind your method.',exZh:'解释你方法背后的依据。'},
{id:'ac057',dim:'academic',level:2,word:'data',phonetic:'/ˈdeɪtə/',zh:'数据',example:'The data was collected over six months.',exZh:'数据在六个月内收集完成。'},
{id:'ac058',dim:'academic',level:3,word:'triangulation',phonetic:'/traɪˌæŋɡjʊˈleɪʃən/',zh:'三角验证法',example:'Triangulation strengthens research validity.',exZh:'三角验证法增强了研究的有效性。'},
{id:'ac059',dim:'academic',level:3,word:'annotate',phonetic:'/ˈænəteɪt/',zh:'注释/批注',example:'Annotate the sources as you read.',exZh:'阅读时对文献进行批注。'},
{id:'ac060',dim:'academic',level:3,word:'evaluate',phonetic:'/ɪˈvæljueɪt/',zh:'评估',example:'Evaluate the strengths and weaknesses of the argument.',exZh:'评估论点的优势和不足。'},
{id:'ac061',dim:'academic',level:3,word:'postulate',phonetic:'/ˈpɒstjʊleɪt/',zh:'假设/推断',example:'The researcher postulated a link between the two.',exZh:'研究者假设两者之间存在联系。'},
{id:'ac062',dim:'academic',level:3,word:'longitudinal',phonetic:'/ˌlɒŋɡɪˈtjuːdɪnəl/',zh:'纵向的',example:'A longitudinal study tracks subjects over years.',exZh:'纵向研究追踪受试者多年。'},
{id:'ac063',dim:'academic',level:3,word:'validity',phonetic:'/vəˈlɪdɪti/',zh:'有效性',example:'Internal validity is crucial to research design.',exZh:'内部有效性对研究设计至关重要。'},
{id:'ac064',dim:'academic',level:3,word:'reliability',phonetic:'/rɪˌlaɪəˈbɪlɪti/',zh:'可靠性',example:'The test showed high reliability across groups.',exZh:'该测试在各组中均显示出高可靠性。'},
{id:'ac065',dim:'academic',level:3,word:'generalise',phonetic:'/ˈdʒɛnərəlaɪz/',zh:'概括/推广',example:'Be cautious when generalising from small samples.',exZh:'从小样本概括时要谨慎。'},
{id:'ac066',dim:'academic',level:4,word:'epistemological',phonetic:'/ɪˌpɪstɪməˈlɒdʒɪkəl/',zh:'认识论的',example:'The paper takes an epistemological approach.',exZh:'该论文采用了认识论的研究方法。'},
{id:'ac067',dim:'academic',level:4,word:'normative',phonetic:'/ˈnɔːrmətɪv/',zh:'规范性的',example:'The study raises normative questions about justice.',exZh:'该研究提出了关于正义的规范性问题。'},
{id:'ac068',dim:'academic',level:4,word:'discursive',phonetic:'/dɪˈskɜːrsɪv/',zh:'话语的/叙述性的',example:'The discursive analysis examined media framing.',exZh:'话语分析检视了媒体的叙事框架。'},
{id:'ac069',dim:'academic',level:4,word:'reflexivity',phonetic:'/ˌriːflɛkˈsɪvɪti/',zh:'反思性',example:'Reflexivity requires researchers to examine their own biases.',exZh:'反思性要求研究者审视自身的偏见。'},
{id:'ac070',dim:'academic',level:4,word:'ontological',phonetic:'/ˌɒntəˈlɒdʒɪkəl/',zh:'本体论的',example:'The debate has an ontological dimension.',exZh:'这场辩论具有本体论层面的意义。'},
{id:'ac071',dim:'academic',level:4,word:'inductive',phonetic:'/ɪnˈdʌktɪv/',zh:'归纳的',example:'Inductive reasoning builds theory from data.',exZh:'归纳推理从数据中建立理论。'},
{id:'ac072',dim:'academic',level:4,word:'deductive',phonetic:'/dɪˈdʌktɪv/',zh:'演绎的',example:'Deductive reasoning tests a hypothesis.',exZh:'演绎推理用于检验假设。'},
{id:'ac073',dim:'academic',level:4,word:'speculative',phonetic:'/ˈspɛkjʊlətɪv/',zh:'推测性的',example:'Without evidence, the claim remains speculative.',exZh:'没有证据，该主张仍属推测性的。'},
{id:'ac074',dim:'academic',level:5,word:'falsifiability',phonetic:'/ˌfɒlsɪfaɪəˈbɪlɪti/',zh:'可证伪性',example:'Popper argued that falsifiability defines science.',exZh:'波普尔认为可证伪性界定了科学。'},
{id:'ac075',dim:'academic',level:5,word:'phenomenography',phonetic:'/ˌfɛnəˈmɒɡrəfi/',zh:'现象描述研究法',example:'Phenomenography maps variations in experience.',exZh:'现象描述研究法绘制体验的差异图。'},
{id:'ac076',dim:'academic',level:5,word:'interoperability',phonetic:'/ˌɪntərˌɒpərəˈbɪlɪti/',zh:'互操作性',example:'Interoperability between systems is key.',exZh:'系统之间的互操作性至关重要。'},
{id:'ac077',dim:'academic',level:5,word:'heuristics',phonetic:'/hjʊˈrɪstɪks/',zh:'启发式方法',example:'Heuristics guide exploration when data is limited.',exZh:'在数据有限时启发式方法指导探索。'},
{id:'ac078',dim:'academic',level:5,word:'operationalise',phonetic:'/ˌɒpərˈeɪʃənəlaɪz/',zh:'操作化/具体化',example:'How you operationalise a concept affects measurement.',exZh:'如何操作化一个概念会影响测量方式。'},
{id:'ac079',dim:'academic',level:6,word:'axiomatic',phonetic:'/ˌæksiəˈmætɪk/',zh:'公理性的/不言而喻的',example:'The need for evidence is axiomatic in science.',exZh:'证据的必要性在科学中是不言而喻的。'},
{id:'ac080',dim:'academic',level:6,word:'circumscribe',phonetic:'/ˈsɜːrkəmskraɪb/',zh:'限制/约束',example:'The study is circumscribed by its small sample.',exZh:'该研究受其小样本量的限制。'},
{id:'ac081',dim:'academic',level:3,word:'compare',phonetic:'/kəmˈpɛr/',zh:'比较',example:'Compare the two models in your analysis.',exZh:'在分析中比较这两种模型。'},
{id:'ac082',dim:'academic',level:3,word:'contrast',phonetic:'/ˈkɒntrɑːst/',zh:'对比',example:'Contrast the findings with previous research.',exZh:'将研究结果与以往研究进行对比。'},
{id:'ac083',dim:'academic',level:2,word:'classify',phonetic:'/ˈklæsɪfaɪ/',zh:'分类',example:'Classify the responses into three categories.',exZh:'将回答分为三类。'},
{id:'ac084',dim:'academic',level:3,word:'verify',phonetic:'/ˈvɛrɪfaɪ/',zh:'核实/验证',example:'Verify your sources before citing them.',exZh:'引用前先核实你的来源。'},
{id:'ac085',dim:'academic',level:4,word:'replicate',phonetic:'/ˈrɛplɪkeɪt/',zh:'复制/重复实验',example:'The results could not be replicated.',exZh:'结果无法被复制验证。'},
{id:'ac086',dim:'academic',level:4,word:'scrutinise',phonetic:'/ˈskruːtɪnaɪz/',zh:'仔细审查',example:'Scrutinise the data before drawing conclusions.',exZh:'得出结论前仔细审查数据。'},
{id:'ac087',dim:'academic',level:5,word:'explicate',phonetic:'/ˈɛksplɪkeɪt/',zh:'详细阐释',example:'The paper explicates the theory in depth.',exZh:'这篇论文对该理论进行了深入详细的阐释。'},
{id:'ac088',dim:'academic',level:5,word:'problematise',phonetic:'/prɒˈblɛmətaɪz/',zh:'将……问题化',example:'The author problematises assumptions about gender.',exZh:'作者将关于性别的假设问题化。'},
{id:'ac089',dim:'academic',level:6,word:'subaltern',phonetic:'/ˈsʌbəltɜːrn/',zh:'从属阶层/边缘群体',example:'Spivak asked whether the subaltern can speak.',exZh:'斯皮瓦克提问从属阶层能否发声。'},
{id:'ac090',dim:'academic',level:6,word:'logocentrism',phonetic:'/ˈloʊɡoʊˌsɛntrɪzəm/',zh:'逻各斯中心主义',example:'Derrida critiqued logocentrism in Western thought.',exZh:'德里达批判了西方思想中的逻各斯中心主义。'},
{id:'ac091',dim:'academic',level:3,word:'distinguish',phonetic:'/dɪˈstɪŋɡwɪʃ/',zh:'区分',example:'Distinguish between correlation and causation.',exZh:'区分相关性和因果关系。'},
{id:'ac092',dim:'academic',level:4,word:'benchmark',phonetic:'/ˈbɛntʃmɑːrk/',zh:'基准/参照标准',example:'Use prior studies as a benchmark.',exZh:'以先前的研究作为基准。'},
{id:'ac093',dim:'academic',level:4,word:'iterate',phonetic:'/ˈɪtəreɪt/',zh:'反复迭代',example:'The design was iterated based on feedback.',exZh:'设计根据反馈进行了反复迭代。'},
{id:'ac094',dim:'academic',level:5,word:'elucidate',phonetic:'/ɪˈluːsɪdeɪt/',zh:'阐明/解释清楚',example:'The diagram elucidated the process clearly.',exZh:'图表清楚地阐明了该过程。'},
{id:'ac095',dim:'academic',level:5,word:'stipulate',phonetic:'/ˈstɪpjʊleɪt/',zh:'规定/明确要求',example:'The guidelines stipulate a word limit.',exZh:'指南规定了字数限制。'},
{id:'ac096',dim:'academic',level:6,word:'apodeictic',phonetic:'/ˌæpəˈdɪktɪk/',zh:'必然确定的',example:'An apodeictic statement is necessarily true.',exZh:'必然确定的陈述是必然为真的。'},
{id:'ac097',dim:'academic',level:3,word:'cite',phonetic:'/saɪt/',zh:'引用',example:'Cite all sources in the bibliography.',exZh:'在参考书目中列出所有引用来源。'},
{id:'ac098',dim:'academic',level:4,word:'fine-grained',phonetic:'/faɪn ɡreɪnd/',zh:'细粒度的/细致入微的',example:'A fine-grained analysis reveals subtle differences.',exZh:'细粒度分析能揭示细微的差异。'},
{id:'ac099',dim:'academic',level:5,word:'instantiate',phonetic:'/ɪnˈstænʃieɪt/',zh:'例示/具体化',example:'The case study instantiates the theory.',exZh:'案例研究具体展示了这一理论。'},
{id:'ac100',dim:'academic',level:6,word:'prolegomenon',phonetic:'/ˌproʊlɪˈɡɒmɪnɒn/',zh:'导论/前言',example:'The prolegomenon sets up the main argument.',exZh:'导论为主要论点奠定了基础。'},
