// wordbank.js — Foreign词库 v4 · 350词
// daily×50, emotion×50, nature×100, abstract×50, social×50, academic×50

export const DIMENSIONS = {
  daily:    { label:'日常生活', color:'#3b82f6', icon:'☕' },
  emotion:  { label:'情感心理', color:'#f9a8d4', icon:'💭' },
  nature:   { label:'自然世界', color:'#86efac', icon:'🌿' },
  abstract: { label:'抽象概念', color:'#818cf8', icon:'✦'  },
  social:   { label:'社交场景', color:'#fb923c', icon:'🗣'  },
  academic: { label:'学术书面', color:'#6ee7b7', icon:'📖' },
};

export const WORDS = [

// ─── DAILY 日常生活 ×50 ────────────────────────────────────
{id:'d001',dim:'daily',level:1,word:'breakfast',phonetic:'/ˈbrekfəst/',zh:'早餐',example:'I have breakfast at seven every morning.',exZh:'我每天七点吃早餐。'},
{id:'d002',dim:'daily',level:1,word:'commute',phonetic:'/kəˈmjuːt/',zh:'通勤',example:'The commute to work takes about forty minutes.',exZh:'上班通勤大约需要四十分钟。'},
{id:'d003',dim:'daily',level:1,word:'groceries',phonetic:'/ˈɡroʊsəriz/',zh:'杂货/食材',example:'She picks up groceries on the way home.',exZh:'她在回家路上买了食材。'},
{id:'d004',dim:'daily',level:1,word:'laundry',phonetic:'/ˈlɔːndri/',zh:'洗衣',example:'I do laundry every Sunday afternoon.',exZh:'我每周日下午洗衣服。'},
{id:'d005',dim:'daily',level:1,word:'errand',phonetic:'/ˈɛrənd/',zh:'差事/跑腿',example:'I need to run a few errands before noon.',exZh:'我中午之前要跑几个差事。'},
{id:'d006',dim:'daily',level:1,word:'nap',phonetic:'/næp/',zh:'小睡',example:'She takes a short nap after lunch.',exZh:'她午饭后小睡一会儿。'},
{id:'d007',dim:'daily',level:1,word:'receipt',phonetic:'/rɪˈsiːt/',zh:'收据',example:'Keep your receipt in case you want a refund.',exZh:'保留收据以备退款。'},
{id:'d008',dim:'daily',level:1,word:'chore',phonetic:'/tʃɔːr/',zh:'家务杂事',example:'Washing dishes is my least favourite chore.',exZh:'洗碗是我最不喜欢的家务。'},
{id:'d009',dim:'daily',level:2,word:'clutter',phonetic:'/ˈklʌtər/',zh:'杂乱堆积',example:'The desk was covered in clutter.',exZh:'桌子上堆满了杂物。'},
{id:'d010',dim:'daily',level:2,word:'appliance',phonetic:'/əˈplaɪəns/',zh:'家电',example:'The kitchen appliances need replacing.',exZh:'厨房家电需要更换了。'},
{id:'d011',dim:'daily',level:2,word:'budget',phonetic:'/ˈbʌdʒɪt/',zh:'预算',example:'We need to stick to our monthly budget.',exZh:'我们需要坚守月度预算。'},
{id:'d012',dim:'daily',level:2,word:'routine',phonetic:'/ruːˈtiːn/',zh:'日常惯例',example:'A morning routine helps you start the day well.',exZh:'晨间惯例能让你更好地开始一天。'},
{id:'d013',dim:'daily',level:2,word:'utilities',phonetic:'/juːˈtɪlɪtiz/',zh:'水电费',example:'Utilities include electricity, gas, and water.',exZh:'水电费包括电、气和水费。'},
{id:'d014',dim:'daily',level:2,word:'pantry',phonetic:'/ˈpæntri/',zh:'食品储藏室',example:'The pantry was stocked with canned goods.',exZh:'储藏室里存满了罐头食品。'},
{id:'d015',dim:'daily',level:2,word:'invoice',phonetic:'/ˈɪnvɔɪs/',zh:'发票/账单',example:'Please send me the invoice by email.',exZh:'请把发票发到我的邮箱。'},
{id:'d016',dim:'daily',level:2,word:'lease',phonetic:'/liːs/',zh:'租约',example:'They signed a one-year lease on the apartment.',exZh:'他们签了一年的公寓租约。'},
{id:'d017',dim:'daily',level:3,word:'renovate',phonetic:'/ˈrɛnəveɪt/',zh:'翻新装修',example:'They plan to renovate the kitchen next year.',exZh:'他们计划明年翻新厨房。'},
{id:'d018',dim:'daily',level:3,word:'overdue',phonetic:'/ˌoʊvərˈdjuː/',zh:'逾期的',example:'This dentist visit is long overdue.',exZh:'这次看牙拖了太久了。'},
{id:'d019',dim:'daily',level:3,word:'hassle',phonetic:'/ˈhæsəl/',zh:'麻烦事',example:'Parking downtown is such a hassle.',exZh:'在市中心停车真是麻烦。'},
{id:'d020',dim:'daily',level:3,word:'staple',phonetic:'/ˈsteɪpəl/',zh:'主食/必需品',example:'Rice is a staple food in many Asian countries.',exZh:'大米是许多亚洲国家的主食。'},
{id:'d021',dim:'daily',level:3,word:'amenity',phonetic:'/əˈmenɪti/',zh:'便利设施',example:'The hotel offered every modern amenity.',exZh:'这家酒店提供了所有现代化便利设施。'},
{id:'d022',dim:'daily',level:3,word:'commuter',phonetic:'/kəˈmjuːtər/',zh:'通勤者',example:'Commuters packed the morning train.',exZh:'通勤者挤满了早班列车。'},
{id:'d023',dim:'daily',level:4,word:'declutter',phonetic:'/diːˈklʌtər/',zh:'整理清空',example:'She spent the weekend decluttering her wardrobe.',exZh:'她花了整个周末整理衣橱。'},
{id:'d024',dim:'daily',level:4,word:'insomnia',phonetic:'/ɪnˈsɒmniə/',zh:'失眠',example:'Stress at work triggered his insomnia.',exZh:'工作压力引发了他的失眠。'},
{id:'d025',dim:'daily',level:4,word:'sedentary',phonetic:'/ˈsɛdənteri/',zh:'久坐不动的',example:'A sedentary lifestyle increases health risks.',exZh:'久坐不动的生活方式会增加健康风险。'},
{id:'d026',dim:'daily',level:4,word:'intermittent',phonetic:'/ˌɪntərˈmɪtənt/',zh:'间歇性的',example:'He practices intermittent fasting twice a week.',exZh:'他每周两次进行间歇性禁食。'},
{id:'d027',dim:'daily',level:4,word:'subsistence',phonetic:'/səbˈsɪstəns/',zh:'维持生计',example:'Many families struggle for basic subsistence.',exZh:'许多家庭为基本生计而挣扎。'},
{id:'d028',dim:'daily',level:5,word:'meticulous',phonetic:'/mɪˈtɪkjʊləs/',zh:'一丝不苟的',example:'He is meticulous about keeping records.',exZh:'他在记录方面一丝不苟。'},
{id:'d029',dim:'daily',level:5,word:'frugal',phonetic:'/ˈfruːɡəl/',zh:'节俭的',example:'Living frugally allowed her to retire early.',exZh:'节俭生活让她得以提前退休。'},
{id:'d030',dim:'daily',level:5,word:'procrastinate',phonetic:'/prəˈkræstɪneɪt/',zh:'拖延',example:'Stop procrastinating and just start.',exZh:'别再拖延了，直接开始吧。'},
{id:'d031',dim:'daily',level:5,word:'austerity',phonetic:'/ɒˈsterɪti/',zh:'紧缩/节俭',example:'Years of austerity left little room for spending.',exZh:'多年的紧缩政策让消费空间所剩无几。'},
{id:'d032',dim:'daily',level:5,word:'ergonomic',phonetic:'/ˌɜːrɡəˈnɒmɪk/',zh:'人体工学的',example:'An ergonomic chair reduces back pain.',exZh:'人体工学椅可以减少背痛。'},
{id:'d033',dim:'daily',level:6,word:'quotidian',phonetic:'/kwəˈtɪdiən/',zh:'日常平凡的',example:'She found beauty in the quotidian moments of life.',exZh:'她在生活的日常琐事中发现了美。'},
{id:'d034',dim:'daily',level:6,word:'penurious',phonetic:'/pɪˈnjʊəriəs/',zh:'极度贫困的',example:'A penurious childhood shaped his frugal habits.',exZh:'极度贫困的童年塑造了他节俭的习惯。'},
{id:'d035',dim:'daily',level:1,word:'alarm',phonetic:'/əˈlɑːrm/',zh:'闹钟/警报',example:'I set my alarm for six every morning.',exZh:'我每天早上六点定闹钟。'},
{id:'d036',dim:'daily',level:1,word:'queue',phonetic:'/kjuː/',zh:'排队',example:'We queued for an hour to get tickets.',exZh:'我们排队一个小时买票。'},
{id:'d037',dim:'daily',level:2,word:'neighbourhood',phonetic:'/ˈneɪbəhʊd/',zh:'街区/邻里',example:'It is a quiet and friendly neighbourhood.',exZh:'这是一个安静友好的街区。'},
{id:'d038',dim:'daily',level:2,word:'tidy',phonetic:'/ˈtaɪdi/',zh:'整洁的/整理',example:'She likes to keep her desk tidy.',exZh:'她喜欢保持桌面整洁。'},
{id:'d039',dim:'daily',level:3,word:'mortgage',phonetic:'/ˈmɔːrɡɪdʒ/',zh:'房贷/抵押贷款',example:'They took out a mortgage to buy the house.',exZh:'他们贷款买了这栋房子。'},
{id:'d040',dim:'daily',level:3,word:'tenant',phonetic:'/ˈtɛnənt/',zh:'租户',example:'The tenant paid rent on time every month.',exZh:'租户每月按时交租。'},
{id:'d041',dim:'daily',level:4,word:'prerogative',phonetic:'/prɪˈrɒɡətɪv/',zh:'特权/专属权利',example:'Changing your mind is your prerogative.',exZh:'改变主意是你的权利。'},
{id:'d042',dim:'daily',level:4,word:'discretionary',phonetic:'/dɪˈskreʃəneri/',zh:'可自由支配的',example:'Discretionary spending fell during the recession.',exZh:'经济衰退期间可支配消费大幅下降。'},
{id:'d043',dim:'daily',level:5,word:'deprivation',phonetic:'/ˌdeprɪˈveɪʃən/',zh:'剥夺/匮乏',example:'Sleep deprivation affects concentration.',exZh:'睡眠剥夺会影响注意力。'},
{id:'d044',dim:'daily',level:5,word:'mundane',phonetic:'/mʌnˈdeɪn/',zh:'平凡无趣的',example:'Even mundane tasks can feel meaningful.',exZh:'就算是平凡无趣的任务也可以充满意义。'},
{id:'d045',dim:'daily',level:6,word:'circadian',phonetic:'/sɜːˈkeɪdiən/',zh:'昼夜节律的',example:'Shift work disrupts your circadian rhythm.',exZh:'轮班工作会扰乱你的昼夜节律。'},
{id:'d046',dim:'daily',level:2,word:'schedule',phonetic:'/ˈʃedjuːl/',zh:'日程安排',example:'My schedule is packed this week.',exZh:'这周我的日程排得很满。'},
{id:'d047',dim:'daily',level:3,word:'allocate',phonetic:'/ˈæləkeɪt/',zh:'分配/拨出',example:'Allocate time for rest each day.',exZh:'每天为休息留出时间。'},
{id:'d048',dim:'daily',level:4,word:'accumulate',phonetic:'/əˈkjuːmjʊleɪt/',zh:'积累',example:'Clutter accumulates when you stop tidying.',exZh:'一旦停止整理，杂物就会堆积起来。'},
{id:'d049',dim:'daily',level:5,word:'pragmatic',phonetic:'/præɡˈmætɪk/',zh:'务实的',example:'She took a pragmatic approach to saving money.',exZh:'她采取了务实的存钱方法。'},
{id:'d050',dim:'daily',level:6,word:'ostentation',phonetic:'/ˌɒstenˈteɪʃən/',zh:'炫耀/卖弄',example:'He lived simply, free from ostentation.',exZh:'他生活简朴，毫无炫耀之气。'},

// ─── EMOTION 情感心理 ×50 ──────────────────────────────────
{id:'e001',dim:'emotion',level:1,word:'nervous',phonetic:'/ˈnɜːrvəs/',zh:'紧张的',example:'I was nervous before the presentation.',exZh:'演讲前我很紧张。'},
{id:'e002',dim:'emotion',level:1,word:'relieved',phonetic:'/rɪˈliːvd/',zh:'如释重负的',example:'She felt relieved after hearing the good news.',exZh:'听到好消息后她如释重负。'},
{id:'e003',dim:'emotion',level:1,word:'frustrated',phonetic:'/ˈfrʌstreɪtɪd/',zh:'沮丧的',example:'He felt frustrated when the plan failed.',exZh:'计划失败时他感到沮丧。'},
{id:'e004',dim:'emotion',level:1,word:'lonely',phonetic:'/ˈloʊnli/',zh:'孤独的',example:'Moving abroad made her feel lonely at first.',exZh:'刚出国时她感到很孤独。'},
{id:'e005',dim:'emotion',level:1,word:'grateful',phonetic:'/ˈɡreɪtfʊl/',zh:'感激的',example:'I am truly grateful for your help.',exZh:'我真心感激你的帮助。'},
{id:'e006',dim:'emotion',level:2,word:'overwhelmed',phonetic:'/ˌoʊvərˈwɛlmd/',zh:'不堪重负的',example:'She felt overwhelmed by all the deadlines.',exZh:'她被一堆截止日期压得喘不过气。'},
{id:'e007',dim:'emotion',level:2,word:'nostalgic',phonetic:'/nɒˈstælʤɪk/',zh:'怀旧的',example:'Old songs always make me nostalgic.',exZh:'老歌总让我怀旧。'},
{id:'e008',dim:'emotion',level:2,word:'envious',phonetic:'/ˈɛnviəs/',zh:'羡慕的',example:'I am envious of her confidence.',exZh:'我很羡慕她的自信。'},
{id:'e009',dim:'emotion',level:2,word:'content',phonetic:'/kənˈtɛnt/',zh:'满足的',example:'She was content with a simple life.',exZh:'她对简单的生活感到满足。'},
{id:'e010',dim:'emotion',level:2,word:'anxious',phonetic:'/ˈæŋkʃəs/',zh:'焦虑的',example:'He was anxious about the exam results.',exZh:'他对考试结果感到焦虑。'},
{id:'e011',dim:'emotion',level:2,word:'bittersweet',phonetic:'/ˌbɪtərˈswiːt/',zh:'苦乐参半的',example:'Graduation is always a bittersweet moment.',exZh:'毕业总是一个苦乐参半的时刻。'},
{id:'e012',dim:'emotion',level:3,word:'apprehensive',phonetic:'/ˌæprɪˈhɛnsɪv/',zh:'忧虑的',example:'She was apprehensive about moving abroad.',exZh:'她对出国移居感到忧虑。'},
{id:'e013',dim:'emotion',level:3,word:'elated',phonetic:'/ɪˈleɪtɪd/',zh:'欣喜若狂的',example:'The team was elated after winning.',exZh:'获胜后团队欣喜若狂。'},
{id:'e014',dim:'emotion',level:3,word:'resentful',phonetic:'/rɪˈzɛntfʊl/',zh:'愤愤不平的',example:'He felt resentful about being overlooked.',exZh:'被忽视让他感到愤愤不平。'},
{id:'e015',dim:'emotion',level:3,word:'vulnerable',phonetic:'/ˈvʌlnərəbəl/',zh:'脆弱的',example:'Sharing feelings can feel vulnerable.',exZh:'分享感受有时会让人感到脆弱。'},
{id:'e016',dim:'emotion',level:3,word:'wistful',phonetic:'/ˈwɪstfʊl/',zh:'惆怅渴望的',example:'She gave a wistful smile at the old photo.',exZh:'她对着老照片露出惆怅的微笑。'},
{id:'e017',dim:'emotion',level:3,word:'indifferent',phonetic:'/ɪnˈdɪfərənt/',zh:'漠然的',example:'He seemed indifferent to the outcome.',exZh:'他对结果似乎漠然置之。'},
{id:'e018',dim:'emotion',level:4,word:'ambivalent',phonetic:'/æmˈbɪvələnt/',zh:'矛盾的',example:'I feel ambivalent about leaving this job.',exZh:'对于离职，我心情很矛盾。'},
{id:'e019',dim:'emotion',level:4,word:'despondent',phonetic:'/dɪˈspɒndənt/',zh:'沮丧绝望的',example:'After weeks of rejection, he grew despondent.',exZh:'几周被拒后他越来越绝望。'},
{id:'e020',dim:'emotion',level:4,word:'exasperated',phonetic:'/ɪɡˈzæspəreɪtɪd/',zh:'极度恼怒的',example:'She was exasperated by the repeated delays.',exZh:'一再拖延让她极为恼火。'},
{id:'e021',dim:'emotion',level:4,word:'remorseful',phonetic:'/rɪˈmɔːrsfʊl/',zh:'悔恨的',example:'He was deeply remorseful for his mistake.',exZh:'他对自己的错误深感悔恨。'},
{id:'e022',dim:'emotion',level:4,word:'forlorn',phonetic:'/fəˈlɔːrn/',zh:'凄凉孤寂的',example:'A forlorn figure sat alone on the bench.',exZh:'一个孤寂的身影独自坐在长椅上。'},
{id:'e023',dim:'emotion',level:5,word:'disillusionment',phonetic:'/ˌdɪsɪˈluːʒənmənt/',zh:'幻灭感',example:'His disillusionment with politics grew over time.',exZh:'他对政治的幻灭感与日俱增。'},
{id:'e024',dim:'emotion',level:5,word:'equanimity',phonetic:'/ˌɛkwəˈnɪmɪti/',zh:'内心平静',example:'She faced the crisis with remarkable equanimity.',exZh:'她以惊人的内心平静面对危机。'},
{id:'e025',dim:'emotion',level:5,word:'cathartic',phonetic:'/kəˈθɑːrtɪk/',zh:'宣泄净化的',example:'Crying during a film can be cathartic.',exZh:'在电影中哭泣有时能宣泄情绪。'},
{id:'e026',dim:'emotion',level:5,word:'stoic',phonetic:'/ˈstoʊɪk/',zh:'坚忍的',example:'He remained stoic throughout the ordeal.',exZh:'他在整个磨难中始终保持坚忍。'},
{id:'e027',dim:'emotion',level:5,word:'introspective',phonetic:'/ˌɪntrəˈspɛktɪv/',zh:'内省的',example:'She became more introspective after the loss.',exZh:'失去亲人后她变得更加内省。'},
{id:'e028',dim:'emotion',level:6,word:'melancholy',phonetic:'/ˈmɛlənkɒli/',zh:'忧郁',example:'A gentle melancholy settled over the empty house.',exZh:'一种淡淡的忧郁笼罩着空荡的房子。'},
{id:'e029',dim:'emotion',level:6,word:'ineffable',phonetic:'/ɪnˈɛfəbəl/',zh:'难以言喻的',example:'The view was filled with ineffable sadness.',exZh:'那景色充满了难以言喻的悲伤。'},
{id:'e030',dim:'emotion',level:6,word:'saudade',phonetic:'/saʊˈdɑːdə/',zh:'思念之苦',example:'The music carried a deep sense of saudade.',exZh:'这段音乐承载着深沉的思念之苦。'},
{id:'e031',dim:'emotion',level:1,word:'excited',phonetic:'/ɪkˈsaɪtɪd/',zh:'兴奋的',example:'The children were excited about the trip.',exZh:'孩子们对这次旅行感到兴奋。'},
{id:'e032',dim:'emotion',level:1,word:'scared',phonetic:'/skɛrd/',zh:'害怕的',example:'She was scared of the dark.',exZh:'她害怕黑暗。'},
{id:'e033',dim:'emotion',level:2,word:'embarrassed',phonetic:'/ɪmˈbærəst/',zh:'尴尬的',example:'He was embarrassed by the mistake.',exZh:'他为那个错误感到尴尬。'},
{id:'e034',dim:'emotion',level:2,word:'hopeful',phonetic:'/ˈhoʊpfʊl/',zh:'充满希望的',example:'She remained hopeful despite the setbacks.',exZh:'尽管遭遇挫折，她仍充满希望。'},
{id:'e035',dim:'emotion',level:3,word:'cynical',phonetic:'/ˈsɪnɪkəl/',zh:'愤世嫉俗的',example:'Years of disappointment made him cynical.',exZh:'多年的失望让他变得愤世嫉俗。'},
{id:'e036',dim:'emotion',level:3,word:'bewildered',phonetic:'/bɪˈwɪldərd/',zh:'困惑不解的',example:'She looked bewildered by the sudden change.',exZh:'她对突如其来的变化感到困惑不解。'},
{id:'e037',dim:'emotion',level:4,word:'conflicted',phonetic:'/kənˈflɪktɪd/',zh:'内心挣扎的',example:'He felt conflicted between duty and desire.',exZh:'他在责任与欲望之间感到内心挣扎。'},
{id:'e038',dim:'emotion',level:4,word:'nonchalant',phonetic:'/ˌnɒnʃəˈlɑːnt/',zh:'漫不经心的',example:'She was nonchalant about the whole affair.',exZh:'她对这整件事漫不经心。'},
{id:'e039',dim:'emotion',level:5,word:'perturbation',phonetic:'/ˌpɜːrtərˈbeɪʃən/',zh:'心神不宁',example:'His sudden departure caused her great perturbation.',exZh:'他的突然离去让她心神不宁。'},
{id:'e040',dim:'emotion',level:5,word:'ennui',phonetic:'/ˌɒnˈwiː/',zh:'倦怠百无聊赖',example:'A deep ennui settled over her long vacation.',exZh:'漫长的假期让她陷入了深深的倦怠。'},
{id:'e041',dim:'emotion',level:6,word:'angst',phonetic:'/æŋst/',zh:'深切的焦虑感',example:'Teenage angst is a universal experience.',exZh:'青少年时期的焦虑感是普遍体验。'},
{id:'e042',dim:'emotion',level:6,word:'schadenfreude',phonetic:'/ˈʃɑːdənfrɔɪdə/',zh:'幸灾乐祸',example:'He felt a twinge of schadenfreude at his rival\'s fall.',exZh:'看到对手跌倒，他心中闪过一丝幸灾乐祸。'},
{id:'e043',dim:'emotion',level:3,word:'compassionate',phonetic:'/kəmˈpæʃənɪt/',zh:'富有同情心的',example:'A compassionate response can change everything.',exZh:'一个富有同情心的回应可以改变一切。'},
{id:'e044',dim:'emotion',level:4,word:'distraught',phonetic:'/dɪˈstrɔːt/',zh:'极度痛苦的',example:'She was distraught after hearing the news.',exZh:'听到这个消息后她极度痛苦。'},
{id:'e045',dim:'emotion',level:4,word:'sullen',phonetic:'/ˈsʌlən/',zh:'闷闷不乐的',example:'He sat in sullen silence after the argument.',exZh:'争吵后他闷闷不乐地沉默着。'},
{id:'e046',dim:'emotion',level:5,word:'magnanimous',phonetic:'/mæɡˈnænɪməs/',zh:'宽宏大量的',example:'The champion was magnanimous in victory.',exZh:'冠军在胜利时表现得宽宏大量。'},
{id:'e047',dim:'emotion',level:5,word:'benevolent',phonetic:'/bɪˈnevələnt/',zh:'仁慈的',example:'A benevolent smile crossed her face.',exZh:'她脸上浮现出仁慈的微笑。'},
{id:'e048',dim:'emotion',level:6,word:'truculent',phonetic:'/ˈtrʌkjʊlənt/',zh:'好斗蛮横的',example:'His truculent attitude alienated his colleagues.',exZh:'他好斗蛮横的态度疏远了同事。'},
{id:'e049',dim:'emotion',level:2,word:'jealous',phonetic:'/ˈdʒɛləs/',zh:'嫉妒的',example:'She was jealous of her sister\'s success.',exZh:'她嫉妒姐姐的成功。'},
{id:'e050',dim:'emotion',level:3,word:'serene',phonetic:'/səˈriːn/',zh:'宁静祥和的',example:'The lake looked serene at dawn.',exZh:'黎明时湖面宁静祥和。'},

// ─── NATURE 自然世界 ×100 ──────────────────────────────────
{id:'n001',dim:'nature',level:1,word:'breeze',phonetic:'/briːz/',zh:'微风',example:'A cool breeze came through the window.',exZh:'一阵凉风从窗户吹进来。'},
{id:'n002',dim:'nature',level:1,word:'horizon',phonetic:'/həˈraɪzən/',zh:'地平线',example:'The sun sank below the horizon.',exZh:'太阳沉到了地平线以下。'},
{id:'n003',dim:'nature',level:1,word:'meadow',phonetic:'/ˈmɛdoʊ/',zh:'草地',example:'Children played in the wide meadow.',exZh:'孩子们在宽阔的草地上玩耍。'},
{id:'n004',dim:'nature',level:1,word:'pebble',phonetic:'/ˈpɛbəl/',zh:'鹅卵石',example:'She skipped a pebble across the pond.',exZh:'她在池塘里打水漂。'},
{id:'n005',dim:'nature',level:1,word:'cliff',phonetic:'/klɪf/',zh:'悬崖',example:'Seabirds nest on the cliff edge.',exZh:'海鸟在悬崖边缘筑巢。'},
{id:'n006',dim:'nature',level:2,word:'canopy',phonetic:'/ˈkænəpi/',zh:'树冠层',example:'Sunlight filtered through the forest canopy.',exZh:'阳光透过林冠层洒落下来。'},
{id:'n007',dim:'nature',level:2,word:'glacier',phonetic:'/ˈɡleɪʃər/',zh:'冰川',example:'The glacier has retreated significantly.',exZh:'冰川已经大幅退缩了。'},
{id:'n008',dim:'nature',level:2,word:'dusk',phonetic:'/dʌsk/',zh:'黄昏',example:'The sky turned orange at dusk.',exZh:'黄昏时天空变成了橙色。'},
{id:'n009',dim:'nature',level:2,word:'estuary',phonetic:'/ˈɛstʃueri/',zh:'河口',example:'Migratory birds flock to the estuary.',exZh:'候鸟成群来到河口。'},
{id:'n010',dim:'nature',level:2,word:'ridge',phonetic:'/rɪdʒ/',zh:'山脊',example:'They hiked along the ridge at sunrise.',exZh:'他们在日出时沿山脊徒步。'},
{id:'n011',dim:'nature',level:2,word:'tide',phonetic:'/taɪd/',zh:'潮汐',example:'The tide was coming in fast.',exZh:'潮水涨得很快。'},
{id:'n012',dim:'nature',level:3,word:'drought',phonetic:'/draʊt/',zh:'干旱',example:'The drought lasted three months.',exZh:'干旱持续了三个月。'},
{id:'n013',dim:'nature',level:3,word:'sediment',phonetic:'/ˈsɛdɪmənt/',zh:'沉积物',example:'Sediment collected at the bottom of the river.',exZh:'沉积物在河底堆积。'},
{id:'n014',dim:'nature',level:3,word:'solstice',phonetic:'/ˈsɒlstɪs/',zh:'至日',example:'The summer solstice is the longest day.',exZh:'夏至是一年中最长的一天。'},
{id:'n015',dim:'nature',level:3,word:'bioluminescence',phonetic:'/ˌbaɪoʊˌluːmɪˈnɛsəns/',zh:'生物发光',example:'The bioluminescence lit up the night sea.',exZh:'生物发光照亮了夜晚的海面。'},
{id:'n016',dim:'nature',level:3,word:'tributary',phonetic:'/ˈtrɪbjʊteri/',zh:'支流',example:'The river has dozens of small tributaries.',exZh:'这条河有几十条小支流。'},
{id:'n017',dim:'nature',level:3,word:'crevasse',phonetic:'/krɪˈvæs/',zh:'冰裂缝',example:'The climber carefully crossed the crevasse.',exZh:'登山者小心翼翼地穿越冰裂缝。'},
{id:'n018',dim:'nature',level:4,word:'permafrost',phonetic:'/ˈpɜːrməfrɒst/',zh:'永冻土',example:'Permafrost is thawing due to climate change.',exZh:'由于气候变化，永冻土正在融化。'},
{id:'n019',dim:'nature',level:4,word:'tundra',phonetic:'/ˈtʌndrə/',zh:'苔原',example:'Few trees grow on the Arctic tundra.',exZh:'北极苔原上几乎没有树木生长。'},
{id:'n020',dim:'nature',level:4,word:'equinox',phonetic:'/ˈiːkwɪnɒks/',zh:'春分/秋分',example:'Day and night are equal at the equinox.',exZh:'春分和秋分时昼夜等长。'},
{id:'n021',dim:'nature',level:4,word:'silt',phonetic:'/sɪlt/',zh:'淤泥/粉沙',example:'The river deposited layers of silt on the banks.',exZh:'河流在岸边沉积了一层层淤泥。'},
{id:'n022',dim:'nature',level:4,word:'biodiversity',phonetic:'/ˌbaɪoʊdaɪˈvɜːrsɪti/',zh:'生物多样性',example:'Rainforests support incredible biodiversity.',exZh:'雨林支撑着令人惊叹的生物多样性。'},
{id:'n023',dim:'nature',level:5,word:'ephemeral',phonetic:'/ɪˈfɛmərəl/',zh:'短暂的',example:'Cherry blossoms are ephemeral and precious.',exZh:'樱花短暂而珍贵。'},
{id:'n024',dim:'nature',level:5,word:'phosphorescent',phonetic:'/ˌfɒsfəˈrɛsənt/',zh:'磷光的',example:'The phosphorescent waves glowed in the dark.',exZh:'磷光海浪在黑暗中发光。'},
{id:'n025',dim:'nature',level:5,word:'topography',phonetic:'/təˈpɒɡrəfi/',zh:'地形/地貌',example:'The topography of the valley is quite varied.',exZh:'山谷的地形非常多变。'},
{id:'n026',dim:'nature',level:5,word:'verdant',phonetic:'/ˈvɜːrdənt/',zh:'翠绿的',example:'The verdant hills stretched to the horizon.',exZh:'翠绿的山丘延伸至地平线。'},
{id:'n027',dim:'nature',level:6,word:'petrichor',phonetic:'/ˈpɛtrɪkɔːr/',zh:'雨后泥土的气息',example:'The petrichor after the storm was calming.',exZh:'暴雨后泥土的气息令人平静。'},
{id:'n028',dim:'nature',level:6,word:'syzygy',phonetic:'/ˈsɪzɪdʒi/',zh:'朔望',example:'A syzygy occurs during a solar eclipse.',exZh:'日食发生时，日月地三点一线。'},
{id:'n029',dim:'nature',level:6,word:'sough',phonetic:'/saʊ/',zh:'风声/叹息声',example:'The sough of the wind through the pines was haunting.',exZh:'风穿过松树的叹息声令人着迷。'},
{id:'n030',dim:'nature',level:1,word:'wave',phonetic:'/weɪv/',zh:'海浪',example:'The waves crashed against the rocks.',exZh:'海浪拍打着礁石。'},
{id:'n031',dim:'nature',level:1,word:'soil',phonetic:'/sɔɪl/',zh:'土壤',example:'Rich soil makes plants grow well.',exZh:'肥沃的土壤让植物茁壮生长。'},
{id:'n032',dim:'nature',level:2,word:'pollen',phonetic:'/ˈpɒlən/',zh:'花粉',example:'Bees carry pollen from flower to flower.',exZh:'蜜蜂将花粉从一朵花带到另一朵花。'},
{id:'n033',dim:'nature',level:2,word:'frost',phonetic:'/frɒst/',zh:'霜',example:'Frost covered the grass on winter mornings.',exZh:'冬天早晨草地上覆盖着霜。'},
{id:'n034',dim:'nature',level:3,word:'erosion',phonetic:'/ɪˈroʊʒən/',zh:'侵蚀',example:'Coastal erosion threatens the village.',exZh:'海岸侵蚀威胁着这个村庄。'},
{id:'n035',dim:'nature',level:3,word:'hibernate',phonetic:'/ˈhaɪbərneɪt/',zh:'冬眠',example:'Bears hibernate throughout the winter.',exZh:'熊整个冬天都在冬眠。'},
{id:'n036',dim:'nature',level:4,word:'arid',phonetic:'/ˈærɪd/',zh:'干旱的',example:'Few plants survive in such arid conditions.',exZh:'很少有植物能在这样干旱的条件下存活。'},
{id:'n037',dim:'nature',level:4,word:'temperate',phonetic:'/ˈtɛmpərɪt/',zh:'温带的/温和的',example:'The UK has a temperate maritime climate.',exZh:'英国拥有温带海洋性气候。'},
{id:'n038',dim:'nature',level:5,word:'alluvial',phonetic:'/əˈluːviəl/',zh:'冲积的',example:'Alluvial plains are ideal for farming.',exZh:'冲积平原非常适合农业。'},
{id:'n039',dim:'nature',level:5,word:'fjord',phonetic:'/fjɔːrd/',zh:'峡湾',example:'The fjord was surrounded by towering cliffs.',exZh:'峡湾四周被高耸的悬崖环绕。'},
{id:'n040',dim:'nature',level:6,word:'apricity',phonetic:'/əˈprɪsɪti/',zh:'冬日暖阳',example:'She sat in the garden enjoying the apricity.',exZh:'她坐在花园里享受冬日暖阳。'},
{id:'n041',dim:'nature',level:3,word:'delta',phonetic:'/ˈdɛltə/',zh:'三角洲',example:'The Nile Delta is one of the world\'s largest.',exZh:'尼罗河三角洲是世界上最大的三角洲之一。'},
{id:'n042',dim:'nature',level:4,word:'precipitation',phonetic:'/prɪˌsɪpɪˈteɪʃən/',zh:'降水量',example:'Annual precipitation has dropped significantly.',exZh:'年降水量大幅下降。'},
{id:'n043',dim:'nature',level:2,word:'summit',phonetic:'/ˈsʌmɪt/',zh:'山顶/峰顶',example:'They reached the summit just before sunset.',exZh:'他们在日落前登上了山顶。'},
{id:'n044',dim:'nature',level:3,word:'monsoon',phonetic:'/mɒnˈsuːn/',zh:'季风/雨季',example:'The monsoon brings heavy rains every July.',exZh:'季风每年七月带来强降雨。'},
{id:'n045',dim:'nature',level:4,word:'lagoon',phonetic:'/ləˈɡuːn/',zh:'泻湖',example:'The lagoon was crystal clear and turquoise.',exZh:'泻湖清澈透明，呈碧绿色。'},
{id:'n046',dim:'nature',level:5,word:'penumbra',phonetic:'/pɪˈnʌmbrə/',zh:'半影/边缘地带',example:'The eclipse cast a deep penumbra across the land.',exZh:'日食在大地上投下了深深的半影。'},
{id:'n047',dim:'nature',level:5,word:'solitude',phonetic:'/ˈsɒlɪtjuːd/',zh:'独处/孤寂',example:'She found peace in the solitude of the mountains.',exZh:'她在山间的独处中找到了平静。'},
{id:'n048',dim:'nature',level:6,word:'noctilucent',phonetic:'/ˌnɒktɪˈluːsənt/',zh:'夜光的',example:'Noctilucent clouds glow after sunset.',exZh:'夜光云在日落后发光。'},
{id:'n049',dim:'nature',level:2,word:'avalanche',phonetic:'/ˈævəlɑːntʃ/',zh:'雪崩',example:'Heavy snowfall triggered an avalanche.',exZh:'大雪引发了雪崩。'},
{id:'n050',dim:'nature',level:3,word:'overcast',phonetic:'/ˌoʊvərˈkæst/',zh:'阴天的',example:'The sky was overcast all day.',exZh:'天空整天都是阴的。'},
{id:'n051',dim:'nature',level:1,word:'river',phonetic:'/ˈrɪvər/',zh:'河流',example:'The river flows through the valley.',exZh:'这条河流穿过山谷。'},
{id:'n052',dim:'nature',level:2,word:'mountain',phonetic:'/ˈmaʊntən/',zh:'山脉',example:'Snow covered the top of the mountain.',exZh:'白雪覆盖了山顶。'},
{id:'n053',dim:'nature',level:3,word:'waterfall',phonetic:'/ˈwɔːtərfɔːl/',zh:'瀑布',example:'We heard the waterfall from far away.',exZh:'我们从很远处就听到了瀑布的声音。'},
{id:'n054',dim:'nature',level:4,word:'wetland',phonetic:'/ˈwɛtlænd/',zh:'湿地',example:'Wetlands filter water and support wildlife.',exZh:'湿地净化水源并支撑野生动物生存。'},
{id:'n055',dim:'nature',level:5,word:'ecosystem',phonetic:'/ˈiːkəʊsɪstəm/',zh:'生态系统',example:'A healthy ecosystem supports many species.',exZh:'健康的生态系统支撑着许多物种。'},
{id:'n056',dim:'nature',level:6,word:'coral',phonetic:'/ˈkɒrəl/',zh:'珊瑚',example:'Coral reefs are threatened by rising sea temperatures.',exZh:'珊瑚礁受到海水升温的威胁。'},
{id:'n057',dim:'nature',level:1,word:'tree',phonetic:'/triː/',zh:'树木',example:'A tall tree stood beside the house.',exZh:'房子旁边有一棵高大的树。'},
{id:'n058',dim:'nature',level:2,word:'ocean',phonetic:'/ˈoʊʃən/',zh:'海洋',example:'The ocean looked calm this morning.',exZh:'今天早上海洋看起来很平静。'},
{id:'n059',dim:'nature',level:3,word:'desert',phonetic:'/ˈdɛzərt/',zh:'沙漠',example:'Few plants can survive in the desert.',exZh:'很少有植物能在沙漠中生存。'},
{id:'n060',dim:'nature',level:4,word:'volcano',phonetic:'/vɒlˈkeɪnoʊ/',zh:'火山',example:'The volcano erupted last year.',exZh:'这座火山去年爆发了。'},
{id:'n061',dim:'nature',level:5,word:'habitat',phonetic:'/ˈhæbɪtæt/',zh:'栖息地',example:'Wetlands are an important habitat for birds.',exZh:'湿地是鸟类重要的栖息地。'},
{id:'n062',dim:'nature',level:6,word:'photosynthesis',phonetic:'/ˌfoʊtəʊˈsɪnθəsɪs/',zh:'光合作用',example:'Plants use photosynthesis to produce energy.',exZh:'植物通过光合作用产生能量。'},
{id:'n063',dim:'nature',level:1,word:'leaf',phonetic:'/liːf/',zh:'树叶',example:'A yellow leaf fell to the ground.',exZh:'一片黄色的叶子落到了地上。'},
{id:'n064',dim:'nature',level:2,word:'island',phonetic:'/ˈaɪlənd/',zh:'岛屿',example:'They spent the summer on a small island.',exZh:'他们在一个小岛上度过了夏天。'},
{id:'n065',dim:'nature',level:3,word:'thunder',phonetic:'/ˈθʌndər/',zh:'雷声',example:'The thunder shook the windows.',exZh:'雷声震动了窗户。'},
{id:'n066',dim:'nature',level:4,word:'canyon',phonetic:'/ˈkænjən/',zh:'峡谷',example:'The hikers explored the deep canyon.',exZh:'徒步旅行者探索了这条深邃的峡谷。'},
{id:'n067',dim:'nature',level:5,word:'landslide',phonetic:'/ˈlændslaɪd/',zh:'山体滑坡',example:'The landslide blocked the mountain road.',exZh:'山体滑坡堵住了山路。'},
{id:'n068',dim:'nature',level:6,word:'deforestation',phonetic:'/diːˌfɒrɪˈsteɪʃən/',zh:'森林砍伐',example:'Deforestation threatens many animals.',exZh:'森林砍伐威胁着许多动物。'},
{id:'n069',dim:'nature',level:1,word:'flower',phonetic:'/ˈflaʊər/',zh:'花朵',example:'The flower opened in the sunlight.',exZh:'花朵在阳光下绽放了。'},
{id:'n070',dim:'nature',level:2,word:'valley',phonetic:'/ˈvæli/',zh:'山谷',example:'A river runs through the valley.',exZh:'一条河流穿过山谷。'},
{id:'n071',dim:'nature',level:3,word:'rainforest',phonetic:'/ˈreɪnfɒrɪst/',zh:'雨林',example:'The rainforest is home to rare animals.',exZh:'雨林是稀有动物的家园。'},
{id:'n072',dim:'nature',level:4,word:'tsunami',phonetic:'/tsuːˈnɑːmi/',zh:'海啸',example:'The tsunami caused severe damage to the coast.',exZh:'海啸对海岸造成了严重破坏。'},
{id:'n073',dim:'nature',level:5,word:'climate',phonetic:'/ˈklaɪmɪt/',zh:'气候',example:'The region has a warm climate all year.',exZh:'这个地区全年气候温暖。'},
{id:'n074',dim:'nature',level:6,word:'geothermal',phonetic:'/ˌdʒiːoʊˈθɜːrməl/',zh:'地热的',example:'The town uses geothermal energy for heating.',exZh:'这个小镇利用地热能供暖。'},
{id:'n075',dim:'nature',level:1,word:'grass',phonetic:'/ɡræs/',zh:'草地',example:'The grass was wet after the rain.',exZh:'雨后草地湿漉漉的。'},
{id:'n076',dim:'nature',level:2,word:'storm',phonetic:'/stɔːrm/',zh:'暴风雨',example:'The storm lasted all night.',exZh:'暴风雨持续了一整夜。'},
{id:'n077',dim:'nature',level:3,word:'plateau',phonetic:'/ˈplætoʊ/',zh:'高原',example:'The plateau sits two thousand metres above sea level.',exZh:'这片高原海拔两千米。'},
{id:'n078',dim:'nature',level:4,word:'blizzard',phonetic:'/ˈblɪzərd/',zh:'暴风雪',example:'The blizzard trapped travellers for days.',exZh:'暴风雪使旅客被困数日。'},
{id:'n079',dim:'nature',level:5,word:'renewable',phonetic:'/rɪˈnjuːəbəl/',zh:'可再生的',example:'Solar power is a renewable energy source.',exZh:'太阳能是一种可再生能源。'},
{id:'n080',dim:'nature',level:6,word:'conservation',phonetic:'/ˌkɒnsəˈveɪʃən/',zh:'保护',example:'Wildlife conservation is becoming more important.',exZh:'野生动物保护变得越来越重要。'},
{id:'n081',dim:'nature',level:1,word:'rock',phonetic:'/rɒk/',zh:'岩石',example:'The child picked up a smooth rock.',exZh:'那个孩子捡起了一块光滑的岩石。'},
{id:'n082',dim:'nature',level:2,word:'forest',phonetic:'/ˈfɒrɪst/',zh:'森林',example:'The forest was quiet at dawn.',exZh:'黎明时森林十分安静。'},
{id:'n083',dim:'nature',level:3,word:'fog',phonetic:'/fɒɡ/',zh:'雾',example:'Thick fog covered the highway.',exZh:'浓雾笼罩了高速公路。'},
{id:'n084',dim:'nature',level:4,word:'earthquake',phonetic:'/ˈɜːrθkweɪk/',zh:'地震',example:'The earthquake damaged several buildings.',exZh:'地震损坏了几栋建筑。'},
{id:'n085',dim:'nature',level:5,word:'pollution',phonetic:'/pəˈluːʃən/',zh:'污染',example:'Air pollution affects human health.',exZh:'空气污染影响人类健康。'},
{id:'n086',dim:'nature',level:6,word:'endangered',phonetic:'/ɪnˈdeɪndʒərd/',zh:'濒危的',example:'The panda is an endangered species.',exZh:'熊猫是一种濒危物种。'},
{id:'n087',dim:'nature',level:1,word:'lake',phonetic:'/leɪk/',zh:'湖泊',example:'The lake reflected the blue sky.',exZh:'湖面倒映着蓝天。'},
{id:'n088',dim:'nature',level:2,word:'cloud',phonetic:'/klaʊd/',zh:'云',example:'A dark cloud moved across the sky.',exZh:'一朵乌云飘过天空。'},
{id:'n089',dim:'nature',level:3,word:'wildlife',phonetic:'/ˈwaɪldlaɪf/',zh:'野生动物',example:'The park protects local wildlife.',exZh:'这个公园保护当地的野生动物。'},
{id:'n090',dim:'nature',level:4,word:'hurricane',phonetic:'/ˈhʌrɪkən/',zh:'飓风',example:'The hurricane forced people to leave the town.',exZh:'飓风迫使人们离开小镇。'},
{id:'n091',dim:'nature',level:5,word:'atmosphere',phonetic:'/ˈætməsfɪər/',zh:'大气层',example:'The atmosphere traps heat from the sun.',exZh:'大气层吸收来自太阳的热量。'},
{id:'n092',dim:'nature',level:6,word:'sustainability',phonetic:'/səˌsteɪnəˈbɪlɪti/',zh:'可持续性',example:'Sustainability is important for the future of the planet.',exZh:'可持续性对地球的未来非常重要。'},
{id:'n093',dim:'nature',level:1,word:'rain',phonetic:'/reɪn/',zh:'雨',example:'The rain stopped before sunset.',exZh:'太阳落山前雨停了。'},
{id:'n094',dim:'nature',level:2,word:'beach',phonetic:'/biːtʃ/',zh:'海滩',example:'Children played on the beach all day.',exZh:'孩子们在海滩上玩了一整天。'},
{id:'n095',dim:'nature',level:3,word:'jungle',phonetic:'/ˈdʒʌŋɡəl/',zh:'丛林',example:'The jungle was filled with strange sounds.',exZh:'丛林里充满了奇怪的声音。'},
{id:'n096',dim:'nature',level:4,word:'heatwave',phonetic:'/ˈhiːtweɪv/',zh:'热浪',example:'The heatwave broke records across the country.',exZh:'热浪打破了全国各地的纪录。'},
{id:'n097',dim:'nature',level:5,word:'organic',phonetic:'/ɔːrˈɡænɪk/',zh:'有机的',example:'They grow organic vegetables on the farm.',exZh:'他们在农场种植有机蔬菜。'},
{id:'n098',dim:'nature',level:6,word:'extinction',phonetic:'/ɪkˈstɪŋkʃən/',zh:'灭绝',example:'Human activity can lead to species extinction.',exZh:'人类活动可能导致物种灭绝。'},
{id:'n099',dim:'nature',level:1,word:'sun',phonetic:'/sʌn/',zh:'太阳',example:'The sun rose above the hills.',exZh:'太阳从山丘上升起。'},
{id:'n100',dim:'nature',level:2,word:'wind',phonetic:'/wɪnd/',zh:'风',example:'The wind blew strongly by the sea.',exZh:'海边的风吹得很猛烈。'},

// ─── ABSTRACT 抽象概念 ×50 ────────────────────────────────
{id:'a001',dim:'abstract',level:1,word:'progress',phonetic:'/ˈprɒɡrɛs/',zh:'进步',example:'We made good progress today.',exZh:'我们今天取得了很大进步。'},
{id:'a002',dim:'abstract',level:1,word:'freedom',phonetic:'/ˈfriːdəm/',zh:'自由',example:'Freedom means different things to different people.',exZh:'自由对不同的人意味着不同的东西。'},
{id:'a003',dim:'abstract',level:1,word:'justice',phonetic:'/ˈdʒʌstɪs/',zh:'正义',example:'She dedicated her life to justice.',exZh:'她把一生献给了正义事业。'},
{id:'a004',dim:'abstract',level:1,word:'truth',phonetic:'/truːθ/',zh:'真相/真理',example:'The truth was harder than expected.',exZh:'真相比预想的更难以接受。'},
{id:'a005',dim:'abstract',level:2,word:'integrity',phonetic:'/ɪnˈtɛɡrɪti/',zh:'诚信/正直',example:'She acted with integrity under pressure.',exZh:'她在压力下仍保持诚信。'},
{id:'a006',dim:'abstract',level:2,word:'ambiguity',phonetic:'/ˌæmbɪˈɡjuːɪti/',zh:'模糊性/歧义',example:'The contract had too much ambiguity.',exZh:'合同存在太多歧义。'},
{id:'a007',dim:'abstract',level:2,word:'consensus',phonetic:'/kənˈsɛnsəs/',zh:'共识',example:'The team reached a consensus quickly.',exZh:'团队迅速达成了共识。'},
{id:'a008',dim:'abstract',level:2,word:'paradox',phonetic:'/ˈpærədɒks/',zh:'悖论',example:'It is a paradox that more choice leads to less satisfaction.',exZh:'选择越多反而满足感越低，这是一个悖论。'},
{id:'a009',dim:'abstract',level:3,word:'paradigm',phonetic:'/ˈpærədaɪm/',zh:'范式/思维模式',example:'This discovery shifted the scientific paradigm.',exZh:'这一发现改变了科学范式。'},
{id:'a010',dim:'abstract',level:3,word:'resilience',phonetic:'/rɪˈzɪliəns/',zh:'韧性/恢复力',example:'Resilience is the ability to bounce back from failure.',exZh:'韧性是从失败中恢复的能力。'},
{id:'a011',dim:'abstract',level:3,word:'nuance',phonetic:'/ˈnjuːɑːns/',zh:'细微差别',example:'The nuance of the argument was lost in translation.',exZh:'论点的细微差别在翻译中丢失了。'},
{id:'a012',dim:'abstract',level:3,word:'mortality',phonetic:'/mɔːˈtælɪti/',zh:'必死性',example:'Facing illness made him aware of his mortality.',exZh:'面对疾病让他意识到自己终有一死。'},
{id:'a013',dim:'abstract',level:3,word:'irony',phonetic:'/ˈaɪrəni/',zh:'讽刺/反讽',example:'The irony was not lost on anyone.',exZh:'这种讽刺意味人人都能感受到。'},
{id:'a014',dim:'abstract',level:4,word:'subjectivity',phonetic:'/ˌsʌbdʒɛkˈtɪvɪti/',zh:'主观性',example:'Art is defined by its subjectivity.',exZh:'艺术以其主观性为特征。'},
{id:'a015',dim:'abstract',level:4,word:'dichotomy',phonetic:'/daɪˈkɒtəmi/',zh:'二元对立',example:'The false dichotomy of work and life.',exZh:'工作与生活的虚假二元对立。'},
{id:'a016',dim:'abstract',level:4,word:'abstraction',phonetic:'/æbˈstrækʃən/',zh:'抽象化',example:'Math relies heavily on abstraction.',exZh:'数学在很大程度上依赖于抽象化。'},
{id:'a017',dim:'abstract',level:4,word:'relativism',phonetic:'/ˈrɛlətɪvɪzəm/',zh:'相对主义',example:'Moral relativism argues there are no universal truths.',exZh:'道德相对主义认为不存在普世真理。'},
{id:'a018',dim:'abstract',level:4,word:'entropy',phonetic:'/ˈɛntrəpi/',zh:'熵/混乱倾向',example:'Entropy describes a system\'s tendency toward disorder.',exZh:'熵描述了系统趋向无序的倾向。'},
{id:'a019',dim:'abstract',level:5,word:'ontology',phonetic:'/ɒnˈtɒlədʒi/',zh:'本体论',example:'Ontology asks what truly exists.',exZh:'本体论研究什么真正存在。'},
{id:'a020',dim:'abstract',level:5,word:'hegemony',phonetic:'/hɪˈdʒɛməni/',zh:'霸权',example:'Cultural hegemony shapes what we see as normal.',exZh:'文化霸权塑造了我们对"正常"的认知。'},
{id:'a021',dim:'abstract',level:5,word:'liminal',phonetic:'/ˈlɪmɪnəl/',zh:'临界的/过渡期的',example:'Graduation is a liminal moment between two lives.',exZh:'毕业是两段人生之间的临界时刻。'},
{id:'a022',dim:'abstract',level:5,word:'dialectic',phonetic:'/ˌdaɪəˈlɛktɪk/',zh:'辩证法',example:'Hegel\'s dialectic shaped modern philosophy.',exZh:'黑格尔的辩证法塑造了现代哲学。'},
{id:'a023',dim:'abstract',level:5,word:'zeitgeist',phonetic:'/ˈzaɪtɡaɪst/',zh:'时代精神',example:'The film captured the zeitgeist of the 1960s.',exZh:'这部电影捕捉到了20世纪60年代的时代精神。'},
{id:'a024',dim:'abstract',level:6,word:'aporia',phonetic:'/əˈpɔːriə/',zh:'无从解决的困境',example:'The philosopher was stuck in an aporia.',exZh:'哲学家陷入了无从解决的困境。'},
{id:'a025',dim:'abstract',level:6,word:'teleology',phonetic:'/ˌtɛliˈɒlədʒi/',zh:'目的论',example:'Teleology explains events by their purpose.',exZh:'目的论通过事物的目的来解释事件。'},
{id:'a026',dim:'abstract',level:6,word:'tautology',phonetic:'/tɔːˈtɒlədʒi/',zh:'同义反复',example:'"A free gift" is a common tautology.',exZh:'"免费赠品"是一个常见的同义反复。'},
{id:'a027',dim:'abstract',level:2,word:'priority',phonetic:'/praɪˈɒrɪti/',zh:'优先事项',example:'Health should be your top priority.',exZh:'健康应该是你的首要事项。'},
{id:'a028',dim:'abstract',level:3,word:'perspective',phonetic:'/pərˈspɛktɪv/',zh:'视角/观点',example:'Try to see it from a different perspective.',exZh:'试着从不同视角来看这件事。'},
{id:'a029',dim:'abstract',level:3,word:'ideology',phonetic:'/ˌaɪdiˈɒlədʒi/',zh:'意识形态',example:'Their ideology shaped every policy decision.',exZh:'他们的意识形态影响了每一项政策决定。'},
{id:'a030',dim:'abstract',level:4,word:'autonomy',phonetic:'/ɔːˈtɒnəmi/',zh:'自主权',example:'Children need autonomy to develop confidence.',exZh:'孩子需要自主权来培养自信。'},
{id:'a031',dim:'abstract',level:4,word:'sovereignty',phonetic:'/ˈsɒvrɪnti/',zh:'主权',example:'National sovereignty is central to international law.',exZh:'国家主权是国际法的核心。'},
{id:'a032',dim:'abstract',level:5,word:'epistemology',phonetic:'/ɪˌpɪstɪˈmɒlədʒi/',zh:'认识论',example:'Epistemology asks how we know what we know.',exZh:'认识论追问我们如何知道我们所知道的。'},
{id:'a033',dim:'abstract',level:5,word:'determinism',phonetic:'/dɪˈtɜːrmɪnɪzəm/',zh:'决定论',example:'Determinism holds that all events are caused.',exZh:'决定论认为所有事件都是有原因的。'},
{id:'a034',dim:'abstract',level:6,word:'solipsism',phonetic:'/ˈsɒlɪpsɪzəm/',zh:'唯我论',example:'Solipsism is the view that only one\'s own mind exists.',exZh:'唯我论认为只有自己的心智存在。'},
{id:'a035',dim:'abstract',level:1,word:'change',phonetic:'/tʃeɪndʒ/',zh:'变化',example:'Change is the only constant in life.',exZh:'变化是生活中唯一不变的事。'},
{id:'a036',dim:'abstract',level:2,word:'uncertainty',phonetic:'/ʌnˈsɜːrtənti/',zh:'不确定性',example:'Uncertainty can feel uncomfortable.',exZh:'不确定性会让人感到不舒服。'},
{id:'a037',dim:'abstract',level:3,word:'legacy',phonetic:'/ˈlɛɡəsi/',zh:'遗产/影响',example:'She left a lasting legacy in science.',exZh:'她在科学领域留下了持久的影响。'},
{id:'a038',dim:'abstract',level:4,word:'accountability',phonetic:'/əˌkaʊntəˈbɪlɪti/',zh:'问责制',example:'Accountability is key in good governance.',exZh:'问责制是良好治理的关键。'},
{id:'a039',dim:'abstract',level:4,word:'transparency',phonetic:'/trænsˈpærənsi/',zh:'透明度',example:'The public demands transparency from government.',exZh:'公众要求政府保持透明度。'},
{id:'a040',dim:'abstract',level:5,word:'nihilism',phonetic:'/ˈnaɪɪlɪzəm/',zh:'虚无主义',example:'Nihilism rejects all moral and social values.',exZh:'虚无主义否定所有道德和社会价值观。'},
{id:'a041',dim:'abstract',level:3,word:'analogy',phonetic:'/əˈnælədʒi/',zh:'类比',example:'He used an analogy to explain the concept.',exZh:'他用类比来解释这个概念。'},
{id:'a042',dim:'abstract',level:4,word:'precedent',phonetic:'/ˈprɛsɪdənt/',zh:'先例',example:'The ruling set a dangerous precedent.',exZh:'这一裁决开创了危险的先例。'},
{id:'a043',dim:'abstract',level:5,word:'phenomenology',phonetic:'/fɪˌnɒmɪˈnɒlədʒi/',zh:'现象学',example:'Phenomenology studies conscious experience.',exZh:'现象学研究意识体验。'},
{id:'a044',dim:'abstract',level:6,word:'eschatology',phonetic:'/ˌɛskəˈtɒlədʒi/',zh:'末世论',example:'Eschatology deals with the end of times.',exZh:'末世论研究时间的终结。'},
{id:'a045',dim:'abstract',level:2,word:'concept',phonetic:'/ˈkɒnsɛpt/',zh:'概念',example:'The concept was difficult to explain.',exZh:'这个概念很难解释。'},
{id:'a046',dim:'abstract',level:3,word:'bias',phonetic:'/ˈbaɪəs/',zh:'偏见/偏差',example:'Everyone has unconscious bias.',exZh:'每个人都有无意识的偏见。'},
{id:'a047',dim:'abstract',level:4,word:'paradigm shift',phonetic:'/ˈpærədaɪm ʃɪft/',zh:'范式转变',example:'The internet caused a paradigm shift in communication.',exZh:'互联网引发了通信领域的范式转变。'},
{id:'a048',dim:'abstract',level:5,word:'allegory',phonetic:'/ˈæləɡɔːri/',zh:'寓言/象征',example:'The novel is an allegory for political oppression.',exZh:'这部小说是政治压迫的寓言。'},
{id:'a049',dim:'abstract',level:6,word:'apophenia',phonetic:'/ˌæpəˈfiːniə/',zh:'模式幻觉',example:'Seeing faces in clouds is an example of apophenia.',exZh:'在云彩中看到人脸是模式幻觉的一个例子。'},
{id:'a050',dim:'abstract',level:3,word:'contradiction',phonetic:'/ˌkɒntrəˈdɪkʃən/',zh:'矛盾',example:'There is a contradiction in what you said.',exZh:'你说的话存在矛盾。'},

// ─── SOCIAL 社交场景 ×50 ───────────────────────────────────
{id:'s001',dim:'social',level:1,word:'introduce',phonetic:'/ˌɪntrəˈdjuːs/',zh:'介绍',example:'Let me introduce you to my friend.',exZh:'让我介绍你认识我的朋友。'},
{id:'s002',dim:'social',level:1,word:'invitation',phonetic:'/ˌɪnvɪˈteɪʃən/',zh:'邀请',example:'I received an invitation to the party.',exZh:'我收到了派对邀请。'},
{id:'s003',dim:'social',level:1,word:'compliment',phonetic:'/ˈkɒmplɪmənt/',zh:'称赞',example:'She gave him a sincere compliment.',exZh:'她给了他一个真诚的称赞。'},
{id:'s004',dim:'social',level:1,word:'apologize',phonetic:'/əˈpɒlədʒaɪz/',zh:'道歉',example:'He apologized for being late.',exZh:'他为迟到道歉。'},
{id:'s005',dim:'social',level:2,word:'acquaintance',phonetic:'/əˈkweɪntəns/',zh:'熟人',example:'He is an acquaintance, not a close friend.',exZh:'他是个熟人，不是亲密朋友。'},
{id:'s006',dim:'social',level:2,word:'awkward',phonetic:'/ˈɔːkwərd/',zh:'尴尬的',example:'There was an awkward silence at dinner.',exZh:'晚餐时有一段尴尬的沉默。'},
{id:'s007',dim:'social',level:2,word:'gossip',phonetic:'/ˈɡɒsɪp/',zh:'八卦/闲话',example:'Office gossip can damage trust.',exZh:'办公室八卦会损害信任。'},
{id:'s008',dim:'social',level:2,word:'networking',phonetic:'/ˈnɛtwɜːrkɪŋ/',zh:'社交拓展',example:'Networking is essential in this industry.',exZh:'在这个行业，社交拓展至关重要。'},
{id:'s009',dim:'social',level:2,word:'boundary',phonetic:'/ˈbaʊndri/',zh:'界限',example:'Setting boundaries is important in any relationship.',exZh:'在任何关系中设定界限都很重要。'},
{id:'s010',dim:'social',level:3,word:'mediate',phonetic:'/ˈmiːdieɪt/',zh:'调解',example:'She agreed to mediate between the two sides.',exZh:'她同意在双方之间进行调解。'},
{id:'s011',dim:'social',level:3,word:'reciprocate',phonetic:'/rɪˈsɪprəkeɪt/',zh:'回报/互惠',example:'He helped me, and I wanted to reciprocate.',exZh:'他帮了我，我也想回报他。'},
{id:'s012',dim:'social',level:3,word:'confrontation',phonetic:'/ˌkɒnfrʌnˈteɪʃən/',zh:'对峙/冲突',example:'She avoided any confrontation with her boss.',exZh:'她避免与老板发生任何冲突。'},
{id:'s013',dim:'social',level:3,word:'empathy',phonetic:'/ˈɛmpəθi/',zh:'同理心',example:'Good leaders show empathy for their teams.',exZh:'好的领导者会对团队展现同理心。'},
{id:'s014',dim:'social',level:3,word:'compromise',phonetic:'/ˈkɒmprəmaɪz/',zh:'妥协/折中',example:'Every relationship requires compromise.',exZh:'每段关系都需要妥协。'},
{id:'s015',dim:'social',level:3,word:'mentorship',phonetic:'/ˈmɛntərʃɪp/',zh:'师徒关系/指导',example:'Good mentorship accelerates career growth.',exZh:'好的师徒关系能加速职业成长。'},
{id:'s016',dim:'social',level:4,word:'condescending',phonetic:'/ˌkɒndɪˈsɛndɪŋ/',zh:'居高临下的',example:'His tone came across as condescending.',exZh:'他的语气显得居高临下。'},
{id:'s017',dim:'social',level:4,word:'aloof',phonetic:'/əˈluːf/',zh:'冷漠疏远的',example:'She seemed aloof at first but was warm later.',exZh:'她一开始显得冷漠，后来却很热情。'},
{id:'s018',dim:'social',level:4,word:'persuasion',phonetic:'/pərˈsweɪʒən/',zh:'说服',example:'Gentle persuasion worked better than pressure.',exZh:'温和的说服比施压更有效。'},
{id:'s019',dim:'social',level:4,word:'ostracize',phonetic:'/ˈɒstrəsaɪz/',zh:'排挤',example:'They ostracized him after the scandal.',exZh:'丑闻之后他被大家排挤。'},
{id:'s020',dim:'social',level:4,word:'diplomacy',phonetic:'/dɪˈpləʊməsi/',zh:'外交手腕/圆滑',example:'Handling the dispute required great diplomacy.',exZh:'处理这场纠纷需要高超的外交手腕。'},
{id:'s021',dim:'social',level:5,word:'charisma',phonetic:'/kəˈrɪzmə/',zh:'个人魅力',example:'Her charisma drew people to her instantly.',exZh:'她的个人魅力让人对她一见如故。'},
{id:'s022',dim:'social',level:5,word:'sycophant',phonetic:'/ˈsɪkəfænt/',zh:'马屁精',example:'Surrounded by sycophants, he lost touch with reality.',exZh:'被马屁精包围，他脱离了现实。'},
{id:'s023',dim:'social',level:5,word:'deference',phonetic:'/ˈdɛfərəns/',zh:'顺从/尊重权威',example:'She showed deference to her elders.',exZh:'她对长辈表示尊重顺从。'},
{id:'s024',dim:'social',level:5,word:'rapport',phonetic:'/ræˈpɔːr/',zh:'融洽关系',example:'Building rapport takes time and effort.',exZh:'建立融洽关系需要时间和努力。'},
{id:'s025',dim:'social',level:5,word:'passive-aggressive',phonetic:'/ˌpæsɪv əˈɡrɛsɪv/',zh:'被动攻击性的',example:'Ignoring messages is a passive-aggressive behaviour.',exZh:'无视消息是一种被动攻击性行为。'},
{id:'s026',dim:'social',level:6,word:'machination',phonetic:'/ˌmækɪˈneɪʃən/',zh:'阴谋诡计',example:'The coup was the result of years of machination.',exZh:'这场政变是多年阴谋诡计的结果。'},
{id:'s027',dim:'social',level:6,word:'obsequious',phonetic:'/əbˈsiːkwiəs/',zh:'卑躬屈膝的',example:'His obsequious manner irritated everyone.',exZh:'他卑躬屈膝的态度让所有人反感。'},
{id:'s028',dim:'social',level:6,word:'perfidious',phonetic:'/pərˈfɪdiəs/',zh:'背信弃义的',example:'His perfidious betrayal shocked the whole group.',exZh:'他背信弃义的背叛震惊了整个团队。'},
{id:'s029',dim:'social',level:1,word:'greet',phonetic:'/ɡriːt/',zh:'打招呼',example:'She greeted everyone with a warm smile.',exZh:'她面带温暖的微笑向每个人打招呼。'},
{id:'s030',dim:'social',level:2,word:'conflict',phonetic:'/ˈkɒnflɪkt/',zh:'冲突',example:'They resolved the conflict peacefully.',exZh:'他们和平地解决了冲突。'},
{id:'s031',dim:'social',level:3,word:'solidarity',phonetic:'/ˌsɒlɪˈdærɪti/',zh:'团结',example:'The strike showed remarkable solidarity.',exZh:'这次罢工展现了卓越的团结精神。'},
{id:'s032',dim:'social',level:3,word:'consensus',phonetic:'/kənˈsɛnsəs/',zh:'共识',example:'They reached a consensus after long debate.',exZh:'经过长时间讨论，他们达成了共识。'},
{id:'s033',dim:'social',level:4,word:'hierarchy',phonetic:'/ˈhaɪərɑːrki/',zh:'等级制度',example:'The company had a strict hierarchy.',exZh:'这家公司有严格的等级制度。'},
{id:'s034',dim:'social',level:4,word:'taboo',phonetic:'/təˈbuː/',zh:'禁忌',example:'Discussing salary is a taboo in some workplaces.',exZh:'在某些职场中，讨论薪资是禁忌。'},
{id:'s035',dim:'social',level:5,word:'altruism',phonetic:'/ˈæltruɪzəm/',zh:'利他主义',example:'Her altruism inspired everyone around her.',exZh:'她的利他主义精神激励了周围所有人。'},
{id:'s036',dim:'social',level:5,word:'patronize',phonetic:'/ˈpætrənaɪz/',zh:'以高高在上的态度对待',example:'He patronized his younger colleagues.',exZh:'他以高高在上的态度对待年轻同事。'},
{id:'s037',dim:'social',level:2,word:'collaborate',phonetic:'/kəˈlæbəreɪt/',zh:'合作',example:'The two teams collaborated on the project.',exZh:'两个团队合作完成了这个项目。'},
{id:'s038',dim:'social',level:3,word:'negotiate',phonetic:'/nɪˈɡoʊʃieɪt/',zh:'谈判/协商',example:'They negotiated a fair contract.',exZh:'他们谈判达成了一份公平的合同。'},
{id:'s039',dim:'social',level:4,word:'manipulation',phonetic:'/məˌnɪpjʊˈleɪʃən/',zh:'操控',example:'Emotional manipulation is a form of abuse.',exZh:'情感操控是一种虐待。'},
{id:'s040',dim:'social',level:4,word:'clique',phonetic:'/kliːk/',zh:'小圈子/小团体',example:'The office had a tight clique of old employees.',exZh:'办公室里有一群关系紧密的老员工小团体。'},
{id:'s041',dim:'social',level:5,word:'gaslighting',phonetic:'/ˈɡæzlaɪtɪŋ/',zh:'精神操控/煤气灯效应',example:'Gaslighting makes victims doubt their own reality.',exZh:'精神操控让受害者质疑自己的现实感知。'},
{id:'s042',dim:'social',level:6,word:'pariah',phonetic:'/pəˈraɪə/',zh:'被排斥者/社会弃儿',example:'After the scandal, he became a social pariah.',exZh:'丑闻之后，他成了社会弃儿。'},
{id:'s043',dim:'social',level:3,word:'inclusive',phonetic:'/ɪnˈkluːsɪv/',zh:'包容的',example:'The team tried to create an inclusive culture.',exZh:'团队努力创造包容的文化。'},
{id:'s044',dim:'social',level:4,word:'friction',phonetic:'/ˈfrɪkʃən/',zh:'摩擦/不和',example:'There was friction between the two departments.',exZh:'两个部门之间存在摩擦。'},
{id:'s045',dim:'social',level:5,word:'scapegoat',phonetic:'/ˈskeɪpɡoʊt/',zh:'替罪羊',example:'He was made a scapegoat for the company\'s failure.',exZh:'他被当作公司失败的替罪羊。'},
{id:'s046',dim:'social',level:6,word:'ingratiating',phonetic:'/ɪnˈɡreɪʃieɪtɪŋ/',zh:'讨好的/刻意迎合的',example:'His ingratiating smile made her uncomfortable.',exZh:'他讨好式的微笑让她感到不舒服。'},
{id:'s047',dim:'social',level:2,word:'rumour',phonetic:'/ˈruːmər/',zh:'谣言/传言',example:'A rumour spread quickly through the office.',exZh:'一则谣言在办公室里迅速传播。'},
{id:'s048',dim:'social',level:3,word:'peer pressure',phonetic:'/pɪər ˈprɛʃər/',zh:'同伴压力',example:'Peer pressure can influence bad decisions.',exZh:'同伴压力可能导致错误决定。'},
{id:'s049',dim:'social',level:4,word:'etiquette',phonetic:'/ˈɛtɪkɛt/',zh:'礼仪/规矩',example:'Business etiquette varies across cultures.',exZh:'商务礼仪因文化而异。'},
{id:'s050',dim:'social',level:5,word:'gregarious',phonetic:'/ɡrɪˈɡɛəriəs/',zh:'爱交际的',example:'She was gregarious and made friends easily.',exZh:'她生性爱交际，很容易交到朋友。'},

// ─── ACADEMIC 学术书面 ×50 ────────────────────────────────
{id:'ac001',dim:'academic',level:1,word:'research',phonetic:'/rɪˈsɜːrtʃ/',zh:'研究',example:'She conducted research on climate change.',exZh:'她对气候变化进行了研究。'},
{id:'ac002',dim:'academic',level:1,word:'evidence',phonetic:'/ˈɛvɪdəns/',zh:'证据',example:'The evidence clearly supports the theory.',exZh:'证据清楚地支持了这一理论。'},
{id:'ac003',dim:'academic',level:2,word:'hypothesis',phonetic:'/haɪˈpɒθɪsɪs/',zh:'假设',example:'The researchers tested their hypothesis.',exZh:'研究人员检验了他们的假设。'},
{id:'ac004',dim:'academic',level:2,word:'methodology',phonetic:'/ˌmɛθəˈdɒlədʒi/',zh:'方法论',example:'The methodology was clearly explained.',exZh:'方法论被清晰地阐明了。'},
{id:'ac005',dim:'academic',level:2,word:'correlation',phonetic:'/ˌkɒrəˈleɪʃən/',zh:'相关性',example:'Correlation does not imply causation.',exZh:'相关性不等于因果关系。'},
{id:'ac006',dim:'academic',level:2,word:'abstract',phonetic:'/ˈæbstrækt/',zh:'摘要',example:'Read the abstract before the full paper.',exZh:'读正文前先看摘要。'},
{id:'ac007',dim:'academic',level:2,word:'citation',phonetic:'/saɪˈteɪʃən/',zh:'引用/注释',example:'Every claim needs a proper citation.',exZh:'每一个主张都需要适当的引用。'},
{id:'ac008',dim:'academic',level:3,word:'empirical',phonetic:'/ɪmˈpɪrɪkəl/',zh:'实证的',example:'The study provides empirical evidence.',exZh:'该研究提供了实证证据。'},
{id:'ac009',dim:'academic',level:3,word:'inference',phonetic:'/ˈɪnfərəns/',zh:'推断',example:'The detective drew a quick inference.',exZh:'侦探迅速作出推断。'},
{id:'ac010',dim:'academic',level:3,word:'synthesis',phonetic:'/ˈsɪnθɪsɪs/',zh:'综合',example:'Good writing requires synthesis of ideas.',exZh:'好的写作需要综合各种观点。'},
{id:'ac011',dim:'academic',level:3,word:'peer review',phonetic:'/pɪər rɪˈvjuː/',zh:'同行评审',example:'The paper passed rigorous peer review.',exZh:'这篇论文通过了严格的同行评审。'},
{id:'ac012',dim:'academic',level:3,word:'variable',phonetic:'/ˈvɛəriəbəl/',zh:'变量',example:'They controlled all variables in the experiment.',exZh:'他们在实验中控制了所有变量。'},
{id:'ac013',dim:'academic',level:3,word:'thesis',phonetic:'/ˈθiːsɪs/',zh:'论点/学位论文',example:'Her thesis challenged existing assumptions.',exZh:'她的论点挑战了现有的假设。'},
{id:'ac014',dim:'academic',level:4,word:'epistemology',phonetic:'/ɪˌpɪstɪˈmɒlədʒi/',zh:'认识论',example:'Epistemology studies the nature of knowledge.',exZh:'认识论研究知识的本质。'},
{id:'ac015',dim:'academic',level:4,word:'rhetoric',phonetic:'/ˈrɛtərɪk/',zh:'修辞学',example:'His speech was full of political rhetoric.',exZh:'他的演讲充满了政治修辞。'},
{id:'ac016',dim:'academic',level:4,word:'dissertation',phonetic:'/ˌdɪsəˈteɪʃən/',zh:'博士论文',example:'She spent three years on her dissertation.',exZh:'她花了三年写博士论文。'},
{id:'ac017',dim:'academic',level:4,word:'critique',phonetic:'/krɪˈtiːk/',zh:'批评/评论',example:'The critique raised important questions.',exZh:'该评论提出了重要问题。'},
{id:'ac018',dim:'academic',level:4,word:'paradigm',phonetic:'/ˈpærədaɪm/',zh:'范式',example:'A new paradigm emerged in cognitive science.',exZh:'认知科学出现了新的范式。'},
{id:'ac019',dim:'academic',level:4,word:'qualitative',phonetic:'/ˈkwɒlɪtətɪv/',zh:'定性的',example:'Qualitative research explores meaning and experience.',exZh:'定性研究探索意义和体验。'},
{id:'ac020',dim:'academic',level:4,word:'quantitative',phonetic:'/ˈkwɒntɪtətɪv/',zh:'定量的',example:'Quantitative data was collected through surveys.',exZh:'定量数据通过调查收集。'},
{id:'ac021',dim:'academic',level:5,word:'hermeneutics',phonetic:'/ˌhɜːrməˈnjuːtɪks/',zh:'解释学',example:'Hermeneutics focuses on text interpretation.',exZh:'解释学专注于文本诠释。'},
{id:'ac022',dim:'academic',level:5,word:'positivism',phonetic:'/ˈpɒzɪtɪvɪzəm/',zh:'实证主义',example:'Positivism relies on observable facts.',exZh:'实证主义依赖可观察的事实。'},
{id:'ac023',dim:'academic',level:5,word:'deconstruction',phonetic:'/ˌdiːkənˈstrʌkʃən/',zh:'解构主义',example:'Deconstruction challenges fixed meanings in texts.',exZh:'解构主义挑战文本中固定的意义。'},
{id:'ac024',dim:'academic',level:5,word:'juxtaposition',phonetic:'/ˌdʒʌkstəpəˈzɪʃən/',zh:'并置/对比',example:'The author used juxtaposition to highlight contrast.',exZh:'作者用并置手法突出对比。'},
{id:'ac025',dim:'academic',level:5,word:'reductionism',phonetic:'/rɪˈdʌkʃənɪzəm/',zh:'还原论',example:'Reductionism breaks complex systems into parts.',exZh:'还原论将复杂系统拆解为各个部分。'},
{id:'ac026',dim:'academic',level:6,word:'episteme',phonetic:'/ˈɛpɪstiːm/',zh:'知识型(福柯)',example:'Foucault used the concept of episteme.',exZh:'福柯使用了知识型这一概念。'},
{id:'ac027',dim:'academic',level:6,word:'exegesis',phonetic:'/ˌɛksɪˈdʒiːsɪs/',zh:'经文注疏',example:'The scholar produced a careful exegesis.',exZh:'学者进行了细致的经文注疏。'},
{id:'ac028',dim:'academic',level:6,word:'apocryphal',phonetic:'/əˈpɒkrɪfəl/',zh:'真实性存疑的',example:'The story is likely apocryphal but widely told.',exZh:'这个故事真实性存疑，但广为流传。'},
{id:'ac029',dim:'academic',level:1,word:'study',phonetic:'/ˈstʌdi/',zh:'学习/研究',example:'A recent study found surprising results.',exZh:'一项最新研究发现了令人惊讶的结果。'},
{id:'ac030',dim:'academic',level:2,word:'analyse',phonetic:'/ˈænəlaɪz/',zh:'分析',example:'We need to analyse the data carefully.',exZh:'我们需要仔细分析数据。'},
{id:'ac031',dim:'academic',level:3,word:'argument',phonetic:'/ˈɑːrɡjʊmənt/',zh:'论点',example:'Her argument was well-structured and clear.',exZh:'她的论点结构清晰，条理分明。'},
{id:'ac032',dim:'academic',level:3,word:'plagiarism',phonetic:'/ˈpleɪdʒərɪzəm/',zh:'抄袭',example:'Plagiarism is treated seriously in academia.',exZh:'学术界对抄袭行为严肃对待。'},
{id:'ac033',dim:'academic',level:4,word:'ambivalence',phonetic:'/æmˈbɪvələns/'
