// qbank/daily.js — 日常生活场景 · Oxford 3000 核心词
// 约500题，难度A1-C1

export const QBANK_DAILY = [
// ── A1 基础 ──────────────────────────────────────────────
{id:'dy001',scene:'daily',level:1,word:'wake',sentence:'I ___ up at seven every morning.',zh:'我每天早上七点醒来。',hint:'醒来（动词原形）'},
{id:'dy002',scene:'daily',level:1,word:'breakfast',sentence:'She always eats ___ before school.',zh:'她总是在上学前吃早饭。',hint:'早餐'},
{id:'dy003',scene:'daily',level:1,word:'brush',sentence:'Remember to ___ your teeth before bed.',zh:'睡前记得刷牙。',hint:'刷（动词）'},
{id:'dy004',scene:'daily',level:1,word:'shower',sentence:'He takes a ___ every morning.',zh:'他每天早上淋浴。',hint:'淋浴'},
{id:'dy005',scene:'daily',level:1,word:'dress',sentence:'She helped the child ___ for school.',zh:'她帮孩子穿衣服准备上学。',hint:'穿衣（动词）'},
{id:'dy006',scene:'daily',level:1,word:'walk',sentence:'They ___ to the park every afternoon.',zh:'他们每天下午步行去公园。',hint:'步行（动词）'},
{id:'dy007',scene:'daily',level:1,word:'home',sentence:'She arrived ___ late last night.',zh:'她昨晚很晚才到家。',hint:'家'},
{id:'dy008',scene:'daily',level:1,word:'sleep',sentence:'Children need at least nine hours of ___ a night.',zh:'孩子每晚至少需要九小时的睡眠。',hint:'睡眠（名词）'},
{id:'dy009',scene:'daily',level:1,word:'clean',sentence:'She likes to keep her room ___.',zh:'她喜欢保持房间整洁。',hint:'干净的（形容词）'},
{id:'dy010',scene:'daily',level:1,word:'cook',sentence:'My mum loves to ___ on weekends.',zh:'我妈妈喜欢在周末做饭。',hint:'做饭（动词）'},
{id:'dy011',scene:'daily',level:1,word:'wash',sentence:'Please ___ your hands before eating.',zh:'吃饭前请洗手。',hint:'洗（动词）'},
{id:'dy012',scene:'daily',level:1,word:'bed',sentence:'He made his ___ before leaving.',zh:'他出门前整理了床铺。',hint:'床'},
{id:'dy013',scene:'daily',level:1,word:'door',sentence:'Please close the ___ quietly.',zh:'请轻轻关门。',hint:'门'},
{id:'dy014',scene:'daily',level:1,word:'window',sentence:'Open the ___ — it\'s too hot in here.',zh:'把窗户打开，这里太热了。',hint:'窗户'},
{id:'dy015',scene:'daily',level:1,word:'light',sentence:'Turn off the ___ when you leave.',zh:'离开时请关灯。',hint:'灯/灯光'},
{id:'dy016',scene:'daily',level:1,word:'key',sentence:'She lost her ___ and couldn\'t get in.',zh:'她丢了钥匙进不了门。',hint:'钥匙'},
{id:'dy017',scene:'daily',level:1,word:'bag',sentence:'Don\'t forget your ___ on the bus.',zh:'不要把包忘在公交车上。',hint:'包'},
{id:'dy018',scene:'daily',level:1,word:'clock',sentence:'The ___ on the wall shows nine o\'clock.',zh:'墙上的钟显示九点。',hint:'钟'},
{id:'dy019',scene:'daily',level:1,word:'phone',sentence:'She checked her ___ first thing in the morning.',zh:'她早上第一件事就是看手机。',hint:'手机/电话'},
{id:'dy020',scene:'daily',level:1,word:'money',sentence:'He didn\'t have enough ___ to buy lunch.',zh:'他没有足够的钱买午饭。',hint:'钱'},

// ── A2 初级 ──────────────────────────────────────────────
{id:'dy021',scene:'daily',level:2,word:'alarm',sentence:'Set your ___ for six tomorrow morning.',zh:'明天早上把闹钟定在六点。',hint:'闹钟'},
{id:'dy022',scene:'daily',level:2,word:'routine',sentence:'Exercise is part of his daily ___.',zh:'锻炼是他日常惯例的一部分。',hint:'惯例/日常'},
{id:'dy023',scene:'daily',level:2,word:'chore',sentence:'Doing the dishes is my least favourite ___.',zh:'洗碗是我最不喜欢的家务。',hint:'家务杂事'},
{id:'dy024',scene:'daily',level:2,word:'laundry',sentence:'She does the ___ every Sunday.',zh:'她每周日洗衣服。',hint:'洗衣'},
{id:'dy025',scene:'daily',level:2,word:'tidy',sentence:'Please ___ your room before dinner.',zh:'请在晚饭前整理你的房间。',hint:'整理（动词）'},
{id:'dy026',scene:'daily',level:2,word:'rubbish',sentence:'Take the ___ out before you go.',zh:'你走之前把垃圾带出去。',hint:'垃圾'},
{id:'dy027',scene:'daily',level:2,word:'rent',sentence:'The ___ for this flat is very high.',zh:'这套公寓的租金很贵。',hint:'租金'},
{id:'dy028',scene:'daily',level:2,word:'bill',sentence:'The electricity ___ arrived this morning.',zh:'电费账单今早到了。',hint:'账单'},
{id:'dy029',scene:'daily',level:2,word:'neighbour',sentence:'Our ___ always plays loud music at night.',zh:'我们的邻居晚上总是放很大声的音乐。',hint:'邻居'},
{id:'dy030',scene:'daily',level:2,word:'postman',sentence:'The ___ delivered a package this morning.',zh:'邮递员今早送来了一个包裹。',hint:'邮递员'},
{id:'dy031',scene:'daily',level:2,word:'queue',sentence:'We had to ___ for an hour to get in.',zh:'我们排了一个小时的队才进去。',hint:'排队（动词）'},
{id:'dy032',scene:'daily',level:2,word:'receipt',sentence:'Keep your ___ in case you want a refund.',zh:'保留收据以备退款。',hint:'收据'},
{id:'dy033',scene:'daily',level:2,word:'appointment',sentence:'I have a dentist ___ at three.',zh:'我三点有个牙医预约。',hint:'预约/约定'},
{id:'dy034',scene:'daily',level:2,word:'diary',sentence:'She writes in her ___ every evening.',zh:'她每晚都写日记。',hint:'日记'},
{id:'dy035',scene:'daily',level:2,word:'habit',sentence:'Reading before bed is a good ___.',zh:'睡前阅读是个好习惯。',hint:'习惯'},
{id:'dy036',scene:'daily',level:2,word:'lend',sentence:'Can you ___ me your umbrella?',zh:'你能把雨伞借给我吗？',hint:'借出（动词）'},
{id:'dy037',scene:'daily',level:2,word:'borrow',sentence:'May I ___ your pen for a moment?',zh:'我可以借用你的笔一下吗？',hint:'借入（动词）'},
{id:'dy038',scene:'daily',level:2,word:'spend',sentence:'She ___ two hours cleaning the house.',zh:'她花了两个小时打扫房子。',hint:'花费（动词过去式）'},
{id:'dy039',scene:'daily',level:2,word:'weekly',sentence:'She does a ___ shop every Saturday.',zh:'她每周六采购一次。',hint:'每周的（形容词）'},
{id:'dy040',scene:'daily',level:2,word:'schedule',sentence:'Check your ___ before booking anything.',zh:'预订任何东西前先查看你的日程。',hint:'日程表'},

// ── B1 中级 ──────────────────────────────────────────────
{id:'dy041',scene:'daily',level:3,word:'commute',sentence:'His daily ___ takes over an hour each way.',zh:'他每天的通勤单程超过一小时。',hint:'通勤（名词）'},
{id:'dy042',scene:'daily',level:3,word:'mortgage',sentence:'They took out a ___ to buy the house.',zh:'他们贷款买了这栋房子。',hint:'房贷'},
{id:'dy043',scene:'daily',level:3,word:'utilities',sentence:'___ like gas and electricity are expensive here.',zh:'这里的水电煤气等费用很贵。',hint:'公共事业费（复数）'},
{id:'dy044',scene:'daily',level:3,word:'maintenance',sentence:'The building needs regular ___.',zh:'这栋楼需要定期维护。',hint:'维护/保养'},
{id:'dy045',scene:'daily',level:3,word:'renovation',sentence:'The kitchen is undergoing ___.',zh:'厨房正在翻新。',hint:'翻新/装修'},
{id:'dy046',scene:'daily',level:3,word:'appliance',sentence:'All the kitchen ___ are brand new.',zh:'所有厨房电器都是全新的。',hint:'家用电器（单个）'},
{id:'dy047',scene:'daily',level:3,word:'clutter',sentence:'There was too much ___ on her desk.',zh:'她桌子上堆了太多杂物。',hint:'杂乱堆积'},
{id:'dy048',scene:'daily',level:3,word:'recycle',sentence:'Please ___ paper, glass, and plastic.',zh:'请回收纸张、玻璃和塑料。',hint:'回收（动词）'},
{id:'dy049',scene:'daily',level:3,word:'deposit',sentence:'They paid a ___ before moving in.',zh:'他们搬进去之前交了押金。',hint:'押金/存款'},
{id:'dy050',scene:'daily',level:3,word:'landlord',sentence:'The ___ agreed to fix the boiler.',zh:'房东同意修锅炉。',hint:'房东'},
{id:'dy051',scene:'daily',level:3,word:'overdue',sentence:'This library book is two weeks ___.',zh:'这本图书馆的书已经逾期两周了。',hint:'逾期的'},
{id:'dy052',scene:'daily',level:3,word:'allocate',sentence:'Try to ___ time for exercise each day.',zh:'每天尽量为锻炼留出时间。',hint:'分配（动词）'},
{id:'dy053',scene:'daily',level:3,word:'subscription',sentence:'She cancelled her streaming ___.',zh:'她取消了流媒体订阅。',hint:'订阅'},
{id:'dy054',scene:'daily',level:3,word:'hassle',sentence:'Parking in the city centre is such a ___.',zh:'在市中心停车真是麻烦。',hint:'麻烦事'},
{id:'dy055',scene:'daily',level:3,word:'insure',sentence:'Make sure to ___ your valuables before travelling.',zh:'出行前确保为贵重物品投保。',hint:'投保（动词）'},
{id:'dy056',scene:'daily',level:3,word:'warranty',sentence:'The laptop came with a two-year ___.',zh:'这台笔记本电脑附带两年保修。',hint:'保修/质保'},
{id:'dy057',scene:'daily',level:3,word:'routine',sentence:'A consistent morning ___ improves productivity.',zh:'一致的晨间惯例能提高效率。',hint:'惯例'},
{id:'dy058',scene:'daily',level:3,word:'accumulate',sentence:'Dust tends to ___ under the furniture.',zh:'灰尘往往会在家具下面积累。',hint:'积累（动词）'},
{id:'dy059',scene:'daily',level:3,word:'premises',sentence:'Smoking is not allowed on the ___.',zh:'场所内禁止吸烟。',hint:'场所/建筑（复数）'},
{id:'dy060',scene:'daily',level:3,word:'inventory',sentence:'She did an ___ of everything in the flat.',zh:'她对公寓里的所有东西做了清单。',hint:'清单/库存'},

// ── B2 中高级 ────────────────────────────────────────────
{id:'dy061',scene:'daily',level:4,word:'declutter',sentence:'She spent the weekend ___ her wardrobe.',zh:'她花了整个周末整理衣橱。',hint:'清理杂物（动词ing）'},
{id:'dy062',scene:'daily',level:4,word:'insomnia',sentence:'Stress at work triggered his ___.',zh:'工作压力引发了他的失眠。',hint:'失眠'},
{id:'dy063',scene:'daily',level:4,word:'sedentary',sentence:'A ___ lifestyle increases health risks significantly.',zh:'久坐不动的生活方式会大幅增加健康风险。',hint:'久坐不动的'},
{id:'dy064',scene:'daily',level:4,word:'frugal',sentence:'Living ___ allowed her to retire at fifty.',zh:'节俭的生活让她在五十岁退休。',hint:'节俭地（副词）'},
{id:'dy065',scene:'daily',level:4,word:'discretionary',sentence:'___ spending fell sharply during the recession.',zh:'经济衰退期间可支配消费大幅下降。',hint:'可自由支配的'},
{id:'dy066',scene:'daily',level:4,word:'amenity',sentence:'The flat lacks basic ___ like a washing machine.',zh:'这套公寓缺少洗衣机等基本设施。',hint:'便利设施（单数）'},
{id:'dy067',scene:'daily',level:4,word:'lease',sentence:'The ___ expires at the end of the month.',zh:'租约月底到期。',hint:'租约'},
{id:'dy068',scene:'daily',level:4,word:'conveyancing',sentence:'The solicitor handled all the ___ paperwork.',zh:'律师处理了所有的房产转让文件。',hint:'房产转让手续'},
{id:'dy069',scene:'daily',level:4,word:'subsistence',sentence:'Many families in the area live at ___ level.',zh:'该地区许多家庭仅能勉强维持生计。',hint:'维持生计'},
{id:'dy070',scene:'daily',level:4,word:'expenditure',sentence:'Monthly ___ on food has increased by twenty percent.',zh:'每月食品支出增加了百分之二十。',hint:'支出/花费'},
{id:'dy071',scene:'daily',level:4,word:'ergonomic',sentence:'An ___ chair can prevent back problems.',zh:'人体工学椅可以预防背部问题。',hint:'人体工学的'},
{id:'dy072',scene:'daily',level:4,word:'intermittent',sentence:'She uses ___ fasting to manage her weight.',zh:'她用间歇性禁食来控制体重。',hint:'间歇性的'},
{id:'dy073',scene:'daily',level:4,word:'procrastinate',sentence:'Stop ___ and just start the task.',zh:'别再拖延了，直接开始吧。',hint:'拖延（动词ing）'},
{id:'dy074',scene:'daily',level:4,word:'meticulous',sentence:'She is ___ about keeping financial records.',zh:'她在保存财务记录方面一丝不苟。',hint:'一丝不苟的'},
{id:'dy075',scene:'daily',level:4,word:'austerity',sentence:'Years of ___ left little room for luxuries.',zh:'多年的紧缩让奢侈品无处可容。',hint:'紧缩/节俭'},

// ── C1 高级 ──────────────────────────────────────────────
{id:'dy076',scene:'daily',level:5,word:'quotidian',sentence:'She found beauty in the ___ details of life.',zh:'她在生活的日常细节中发现了美。',hint:'日常平凡的（书面词）'},
{id:'dy077',scene:'daily',level:5,word:'circadian',sentence:'Shift work disrupts your ___ rhythm.',zh:'轮班工作会扰乱你的昼夜节律。',hint:'昼夜节律的'},
{id:'dy078',scene:'daily',level:5,word:'mundane',sentence:'Even ___ tasks can be done mindfully.',zh:'就算是平凡无趣的任务也可以用心去做。',hint:'平凡无趣的'},
{id:'dy079',scene:'daily',level:5,word:'ostentation',sentence:'He lived simply, free from any ___.',zh:'他生活简朴，毫无炫耀之气。',hint:'炫耀/卖弄'},
{id:'dy080',scene:'daily',level:5,word:'penurious',sentence:'A ___ childhood shaped his careful spending habits.',zh:'贫困的童年塑造了他谨慎的消费习惯。',hint:'极度贫困的'},
];
