// qbank/food.js — 食物与饮食场景 · Oxford 3000

export const QBANK_FOOD = [
{id:'fd001',scene:'food',level:1,word:'hungry',sentence:'I\'m really ___ — let\'s eat soon.',zh:'我真的很饿，我们快去吃饭吧。',hint:'饥饿的'},
{id:'fd002',scene:'food',level:1,word:'thirsty',sentence:'Have some water if you feel ___.',zh:'如果你感到口渴就喝点水。',hint:'口渴的'},
{id:'fd003',scene:'food',level:1,word:'taste',sentence:'This soup has a wonderful ___.',zh:'这汤的味道好极了。',hint:'味道（名词）'},
{id:'fd004',scene:'food',level:1,word:'cook',sentence:'She loves to ___ Italian food.',zh:'她喜欢做意大利菜。',hint:'烹饪（动词）'},
{id:'fd005',scene:'food',level:1,word:'eat',sentence:'What do you usually ___ for lunch?',zh:'你午饭通常吃什么？',hint:'吃（动词）'},
{id:'fd006',scene:'food',level:1,word:'drink',sentence:'He doesn\'t ___ coffee after six.',zh:'他六点以后不喝咖啡。',hint:'喝（动词）'},
{id:'fd007',scene:'food',level:1,word:'meal',sentence:'Dinner is the main ___ of the day.',zh:'晚饭是一天中最主要的一餐。',hint:'一餐'},
{id:'fd008',scene:'food',level:1,word:'fresh',sentence:'Always buy ___ vegetables from the market.',zh:'总是从市场买新鲜蔬菜。',hint:'新鲜的'},
{id:'fd009',scene:'food',level:1,word:'sweet',sentence:'This cake is too ___ for me.',zh:'这个蛋糕对我来说太甜了。',hint:'甜的'},
{id:'fd010',scene:'food',level:1,word:'spicy',sentence:'I can\'t eat ___ food — it upsets my stomach.',zh:'我不能吃辛辣食物，会让我胃不舒服。',hint:'辛辣的'},
{id:'fd011',scene:'food',level:1,word:'raw',sentence:'Some fish can be eaten ___.',zh:'有些鱼可以生吃。',hint:'生的/未加工的'},
{id:'fd012',scene:'food',level:1,word:'boil',sentence:'___ the eggs for ten minutes.',zh:'把鸡蛋煮十分钟。',hint:'煮（动词原形）'},
{id:'fd013',scene:'food',level:1,word:'fry',sentence:'He likes to ___ eggs for breakfast.',zh:'他早餐喜欢煎鸡蛋。',hint:'煎炸（动词）'},
{id:'fd014',scene:'food',level:1,word:'bake',sentence:'She wants to ___ a birthday cake.',zh:'她想烤一个生日蛋糕。',hint:'烘烤（动词）'},
{id:'fd015',scene:'food',level:1,word:'recipe',sentence:'Follow the ___ carefully.',zh:'仔细按照食谱操作。',hint:'食谱'},
{id:'fd016',scene:'food',level:2,word:'ingredient',sentence:'List all the ___ before you start cooking.',zh:'开始烹饪前列出所有食材。',hint:'食材（单数）'},
{id:'fd017',scene:'food',level:2,word:'portion',sentence:'The ___ sizes at that restaurant are huge.',zh:'那家餐厅的份量很大。',hint:'份量'},
{id:'fd018',scene:'food',level:2,word:'diet',sentence:'She\'s on a strict ___ to lose weight.',zh:'她正在严格节食减肥。',hint:'饮食/节食'},
{id:'fd019',scene:'food',level:2,word:'nutrition',sentence:'Good ___ is essential for children\'s growth.',zh:'良好的营养对儿童成长至关重要。',hint:'营养'},
{id:'fd020',scene:'food',level:2,word:'calorie',sentence:'This snack has only eighty ___.',zh:'这份零食只有八十卡路里。',hint:'卡路里（复数）'},
{id:'fd021',scene:'food',level:2,word:'vegetarian',sentence:'She became ___ three years ago.',zh:'她三年前成为素食者。',hint:'素食者/素食的'},
{id:'fd022',scene:'food',level:2,word:'dairy',sentence:'He avoids ___ products due to an allergy.',zh:'他因过敏而避开乳制品。',hint:'乳制品（形容词）'},
{id:'fd023',scene:'food',level:2,word:'organic',sentence:'They only buy ___ fruit and vegetables.',zh:'他们只买有机水果和蔬菜。',hint:'有机的'},
{id:'fd024',scene:'food',level:2,word:'leftovers',sentence:'We had ___ from last night\'s dinner.',zh:'我们有昨晚晚饭的剩菜。',hint:'剩饭剩菜'},
{id:'fd025',scene:'food',level:2,word:'flavour',sentence:'This cheese has a very strong ___.',zh:'这种奶酪味道非常浓郁。',hint:'风味/味道'},
{id:'fd026',scene:'food',level:2,word:'seasoning',sentence:'Add ___ to taste.',zh:'根据口味加调料。',hint:'调味料'},
{id:'fd027',scene:'food',level:2,word:'portion',sentence:'She only ate half her ___.',zh:'她只吃了一半的份量。',hint:'份/部分'},
{id:'fd028',scene:'food',level:2,word:'takeaway',sentence:'Let\'s order a ___ tonight.',zh:'今晚我们叫外卖吧。',hint:'外卖'},
{id:'fd029',scene:'food',level:2,word:'cuisine',sentence:'Thai ___ is known for its bold flavours.',zh:'泰国菜以其浓郁的风味著称。',hint:'菜系/烹饪'},
{id:'fd030',scene:'food',level:2,word:'appetite',sentence:'I\'ve lost my ___ — I\'m not hungry at all.',zh:'我没有食欲，一点都不饿。',hint:'食欲'},
{id:'fd031',scene:'food',level:3,word:'simmer',sentence:'Let the sauce ___ for twenty minutes.',zh:'让酱汁小火慢炖二十分钟。',hint:'小火慢炖（动词）'},
{id:'fd032',scene:'food',level:3,word:'marinate',sentence:'___ the chicken in lemon juice overnight.',zh:'把鸡肉在柠檬汁里腌制一夜。',hint:'腌制（动词原形）'},
{id:'fd033',scene:'food',level:3,word:'garnish',sentence:'___ the dish with fresh herbs.',zh:'用新鲜香草装饰这道菜。',hint:'装饰/点缀（动词原形）'},
{id:'fd034',scene:'food',level:3,word:'ferment',sentence:'The dough needs time to ___ properly.',zh:'面团需要时间充分发酵。',hint:'发酵（动词）'},
{id:'fd035',scene:'food',level:3,word:'texture',sentence:'The ___ of this bread is perfectly chewy.',zh:'这面包的口感嚼劲十足。',hint:'质地/口感'},
{id:'fd036',scene:'food',level:3,word:'savoury',sentence:'I prefer ___ snacks to sweet ones.',zh:'我更喜欢咸味零食而不是甜的。',hint:'咸味的/美味的'},
{id:'fd037',scene:'food',level:3,word:'wholesome',sentence:'She prepared a ___ meal for the whole family.',zh:'她为全家准备了一顿健康的饭菜。',hint:'有益健康的'},
{id:'fd038',scene:'food',level:3,word:'indulge',sentence:'She occasionally ___ in chocolate cake.',zh:'她偶尔会放纵自己吃巧克力蛋糕。',hint:'放纵（动词）'},
{id:'fd039',scene:'food',level:3,word:'substitute',sentence:'Use honey as a ___ for sugar.',zh:'用蜂蜜代替糖。',hint:'替代品'},
{id:'fd040',scene:'food',level:3,word:'intolerance',sentence:'She has a lactose ___ and avoids milk.',zh:'她有乳糖不耐受，避免喝牛奶。',hint:'不耐受'},
{id:'fd041',scene:'food',level:3,word:'staple',sentence:'Rice is a ___ food across much of Asia.',zh:'大米是亚洲大部分地区的主食。',hint:'主食/必需品'},
{id:'fd042',scene:'food',level:3,word:'bland',sentence:'Hospital food is often described as ___.',zh:'医院的食物常被描述为淡而无味。',hint:'淡而无味的'},
{id:'fd043',scene:'food',level:3,word:'condiment',sentence:'Ketchup is the most popular ___ in the world.',zh:'番茄酱是世界上最受欢迎的调味品。',hint:'调味品'},
{id:'fd044',scene:'food',level:3,word:'portion control',sentence:'___ ___ is key to maintaining a healthy weight.',zh:'控制食量是保持健康体重的关键。',hint:'控制份量（两个词）'},
{id:'fd045',scene:'food',level:3,word:'pasteurise',sentence:'All milk sold here is ___d to kill bacteria.',zh:'这里出售的所有牛奶都经过巴氏杀菌处理。',hint:'巴氏杀菌（动词过去分词）'},
{id:'fd046',scene:'food',level:4,word:'umami',sentence:'Parmesan cheese adds ___ to the dish.',zh:'帕玛森奶酪为这道菜增添了鲜味。',hint:'鲜味（日语借词）'},
{id:'fd047',scene:'food',level:4,word:'gluttonous',sentence:'The ___ feast left everyone feeling ill.',zh:'这场暴食的盛宴让每个人都感到不舒服。',hint:'贪吃的/暴食的'},
{id:'fd048',scene:'food',level:4,word:'palate',sentence:'The wine was chosen to suit every ___.',zh:'这款葡萄酒是为了迎合各种口味而选择的。',hint:'味觉/口味偏好'},
{id:'fd049',scene:'food',level:4,word:'delicacy',sentence:'Bird\'s nest soup is considered a rare ___.',zh:'燕窝汤被视为珍贵的美食。',hint:'美食珍馐'},
{id:'fd050',scene:'food',level:4,word:'ascetic',sentence:'His ___ diet consisted only of vegetables and water.',zh:'他禁欲式的饮食只有蔬菜和水。',hint:'禁欲的/苦行的'},
];
