// qbank/health.js — 健康场景题库
export const QBANK_HEALTH = [
{id:'hl006',scene:'health',level:1,word:'exercise',sentence:'Daily ___ keeps you healthy.',zh:'每天锻炼让你保持健康。',hint:'锻炼'},
{id:'hl007',scene:'health',level:1,word:'water',sentence:'Drink enough ___ every day.',zh:'每天喝足够的水。',hint:'水'},
{id:'hl008',scene:'health',level:1,word:'sleep',sentence:'Good ___ helps your body recover.',zh:'良好的睡眠有助于身体恢复。',hint:'睡眠'},
{id:'hl009',scene:'health',level:1,word:'doctor',sentence:'You should see a ___ if you feel sick.',zh:'如果你感觉不舒服，应该去看医生。',hint:'医生'},
{id:'hl010',scene:'health',level:1,word:'fruit',sentence:'Eating fresh ___ is good for you.',zh:'吃新鲜水果对你有好处。',hint:'水果'},
{id:'hl011',scene:'health',level:1,word:'nurse',sentence:'The ___ checked my temperature.',zh:'护士给我量了体温。',hint:'护士'},
{id:'hl012',scene:'health',level:1,word:'vitamin',sentence:'This ___ helps strengthen your bones.',zh:'这种维生素有助于强化骨骼。',hint:'维生素'},
{id:'hl013',scene:'health',level:1,word:'diet',sentence:'A healthy ___ includes vegetables and fish.',zh:'健康饮食包括蔬菜和鱼。',hint:'饮食'},
{id:'hl014',scene:'health',level:1,word:'fever',sentence:'She stayed home because of a ___.',zh:'她因为发烧待在家里。',hint:'发烧'},
{id:'hl015',scene:'health',level:1,word:'walk',sentence:'A short ___ after dinner is relaxing.',zh:'晚饭后散步很放松。',hint:'散步'},
{id:'hl016',scene:'health',level:2,word:'medicine',sentence:'Take this ___ after meals.',zh:'饭后服用这种药。',hint:'药'},
{id:'hl017',scene:'health',level:2,word:'protein',sentence:'Eggs are rich in ___.',zh:'鸡蛋富含蛋白质。',hint:'蛋白质'},
{id:'hl018',scene:'health',level:2,word:'headache',sentence:'I have a terrible ___ today.',zh:'我今天头疼得厉害。',hint:'头痛'},
{id:'hl019',scene:'health',level:2,word:'clinic',sentence:'The new ___ opens at 8 a.m.',zh:'新诊所早上八点开门。',hint:'诊所'},
{id:'hl020',scene:'health',level:2,word:'muscle',sentence:'Regular training builds ___.',zh:'规律训练可以增强肌肉。',hint:'肌肉'},
{id:'hl021',scene:'health',level:2,word:'stress',sentence:'Too much ___ can affect your sleep.',zh:'压力过大会影响睡眠。',hint:'压力'},
{id:'hl022',scene:'health',level:2,word:'calories',sentence:'This snack contains too many ___.',zh:'这种零食含有太多热量。',hint:'卡路里'},
{id:'hl023',scene:'health',level:2,word:'cough',sentence:'His ___ became worse at night.',zh:'他的咳嗽在晚上变得更严重了。',hint:'咳嗽'},
{id:'hl024',scene:'health',level:2,word:'fitness',sentence:'She goes to the gym to improve her ___.',zh:'她去健身房提升体能。',hint:'健康/体能'},
{id:'hl025',scene:'health',level:2,word:'dentist',sentence:'Visit the ___ twice a year.',zh:'每年去看两次牙医。',hint:'牙医'},
{id:'hl026',scene:'health',level:3,word:'nutrition',sentence:'Good ___ is important for children.',zh:'良好的营养对孩子很重要。',hint:'营养'},
{id:'hl027',scene:'health',level:3,word:'recovery',sentence:'Proper rest speeds up ___.',zh:'适当休息能加快恢复。',hint:'恢复'},
{id:'hl028',scene:'health',level:3,word:'symptom',sentence:'A sore throat is a common ___ of flu.',zh:'喉咙痛是流感的常见症状。',hint:'症状'},
{id:'hl029',scene:'health',level:3,word:'appointment',sentence:'I made a doctor\'s ___ for tomorrow.',zh:'我预约了明天的医生门诊。',hint:'预约'},
{id:'hl030',scene:'health',level:3,word:'balance',sentence:'Work-life ___ is important for mental health.',zh:'工作与生活平衡对心理健康很重要。',hint:'平衡'},
{id:'hl031',scene:'health',level:3,word:'infection',sentence:'The cut may cause an ___.',zh:'这个伤口可能会引起感染。',hint:'感染'},
{id:'hl032',scene:'health',level:3,word:'therapy',sentence:'Physical ___ helped his knee heal.',zh:'物理治疗帮助他的膝盖恢复。',hint:'治疗'},
{id:'hl033',scene:'health',level:3,word:'allergy',sentence:'She has an ___ to peanuts.',zh:'她对花生过敏。',hint:'过敏'},
{id:'hl034',scene:'health',level:3,word:'heartbeat',sentence:'The doctor checked my ___.',zh:'医生检查了我的心跳。',hint:'心跳'},
{id:'hl035',scene:'health',level:3,word:'energy',sentence:'Healthy meals give you more ___.',zh:'健康饮食会给你更多能量。',hint:'能量'},
{id:'hl036',scene:'health',level:4,word:'pressure',sentence:'High blood ___ can be dangerous.',zh:'高血压可能很危险。',hint:'压力/血压'},
{id:'hl037',scene:'health',level:4,word:'hydration',sentence:'Proper ___ is important after exercise.',zh:'运动后适当补水很重要。',hint:'补水'},
{id:'hl038',scene:'health',level:4,word:'treatment',sentence:'The patient responded well to the ___.',zh:'病人对治疗反应良好。',hint:'治疗'},
{id:'hl039',scene:'health',level:4,word:'anxiety',sentence:'Too much ___ can affect your health.',zh:'过度焦虑会影响健康。',hint:'焦虑'},
{id:'hl040',scene:'health',level:4,word:'hospital',sentence:'He stayed in the ___ for three days.',zh:'他在医院住了三天。',hint:'医院'},
{id:'hl041',scene:'health',level:4,word:'immune',sentence:'Sleep helps keep your ___ system strong.',zh:'睡眠有助于保持免疫系统强健。',hint:'免疫的'},
{id:'hl042',scene:'health',level:4,word:'posture',sentence:'Good ___ can reduce back pain.',zh:'良好的姿势可以减轻背痛。',hint:'姿势'},
{id:'hl043',scene:'health',level:4,word:'surgery',sentence:'She recovered quickly after the ___.',zh:'她手术后恢复得很快。',hint:'手术'},
{id:'hl044',scene:'health',level:4,word:'breathing',sentence:'Deep ___ helps you relax.',zh:'深呼吸有助于放松。',hint:'呼吸'},
{id:'hl045',scene:'health',level:4,word:'wellness',sentence:'Meditation improves overall ___.',zh:'冥想能提升整体健康。',hint:'健康状态'},
{id:'hl046',scene:'health',level:5,word:'circulation',sentence:'Exercise improves blood ___.',zh:'运动可以改善血液循环。',hint:'循环'},
{id:'hl047',scene:'health',level:5,word:'diagnosis',sentence:'The doctor gave an early ___.',zh:'医生给出了早期诊断。',hint:'诊断'},
{id:'hl048',scene:'health',level:5,word:'prevention',sentence:'Regular checkups help with disease ___.',zh:'定期体检有助于疾病预防。',hint:'预防'},
{id:'hl049',scene:'health',level:5,word:'rehabilitation',sentence:'The athlete started ___ after the injury.',zh:'这位运动员受伤后开始康复治疗。',hint:'康复治疗'},
{id:'hl050',scene:'health',level:5,word:'nutritionist',sentence:'The ___ suggested a healthier meal plan.',zh:'营养师建议了更健康的饮食计划。',hint:'营养师'},
{id:'hl051',scene:'health',level:5,word:'vaccination',sentence:'The child received a ___ last week.',zh:'那个孩子上周接种了疫苗。',hint:'疫苗接种'},
{id:'hl052',scene:'health',level:5,word:'fatigue',sentence:'Long work hours can cause ___.',zh:'长时间工作会导致疲劳。',hint:'疲劳'},
{id:'hl053',scene:'health',level:5,word:'meditation',sentence:'Daily ___ can calm your mind.',zh:'每天冥想可以让内心平静。',hint:'冥想'},
{id:'hl054',scene:'health',level:5,word:'consultation',sentence:'The doctor scheduled another ___.',zh:'医生安排了另一次会诊。',hint:'咨询/会诊'},
{id:'hl055',scene:'health',level:5,word:'lifestyle',sentence:'A healthy ___ reduces health risks.',zh:'健康的生活方式可以降低健康风险。',hint:'生活方式'},
];
