// qbank/social.js — 社交场景题库
export const QBANK_SOCIAL = [
{id:'sc006',scene:'social',level:1,word:'friend',sentence:'Tom is my closest ___ at school.',zh:'汤姆是我在学校最亲密的朋友。',hint:'朋友'},
{id:'sc007',scene:'social',level:1,word:'hello',sentence:'She smiled and said ___ to everyone.',zh:'她微笑着向每个人打招呼。',hint:'你好'},
{id:'sc008',scene:'social',level:1,word:'party',sentence:'We are going to a birthday ___ tonight.',zh:'今晚我们要去参加一个生日派对。',hint:'派对'},
{id:'sc009',scene:'social',level:1,word:'meet',sentence:'I will ___ my classmates after school.',zh:'放学后我会见我的同学。',hint:'见面'},
{id:'sc010',scene:'social',level:1,word:'talk',sentence:'They like to ___ during lunch break.',zh:'他们喜欢在午休时聊天。',hint:'聊天'},
{id:'sc011',scene:'social',level:1,word:'smile',sentence:'Her warm ___ made everyone comfortable.',zh:'她温暖的微笑让每个人都感到放松。',hint:'微笑'},
{id:'sc012',scene:'social',level:1,word:'invite',sentence:'Did you ___ Jack to the dinner?',zh:'你邀请杰克参加晚餐了吗？',hint:'邀请'},
{id:'sc013',scene:'social',level:1,word:'group',sentence:'Our study ___ meets every Friday.',zh:'我们的学习小组每周五聚会。',hint:'小组'},
{id:'sc014',scene:'social',level:1,word:'share',sentence:'Friends should ___ their feelings honestly.',zh:'朋友之间应该坦诚分享感受。',hint:'分享'},
{id:'sc015',scene:'social',level:1,word:'team',sentence:'Everyone in the ___ worked well together.',zh:'团队里的每个人都合作得很好。',hint:'团队'},
{id:'sc016',scene:'social',level:2,word:'conversation',sentence:'Their ___ lasted for hours at the cafe.',zh:'他们在咖啡馆聊了好几个小时。',hint:'谈话'},
{id:'sc017',scene:'social',level:2,word:'neighbor',sentence:'Our new ___ brought us some cookies.',zh:'我们的新邻居给我们带来了一些饼干。',hint:'邻居'},
{id:'sc018',scene:'social',level:2,word:'introduce',sentence:'Let me ___ you to my colleague.',zh:'让我把你介绍给我的同事。',hint:'介绍'},
{id:'sc019',scene:'social',level:2,word:'welcome',sentence:'Everyone gave her a warm ___.',zh:'每个人都热情欢迎了她。',hint:'欢迎'},
{id:'sc020',scene:'social',level:2,word:'guest',sentence:'Each ___ received a small gift.',zh:'每位客人都收到了一份小礼物。',hint:'客人'},
{id:'sc021',scene:'social',level:2,word:'respect',sentence:'Good friends always show ___ to each other.',zh:'好朋友总是彼此尊重。',hint:'尊重'},
{id:'sc022',scene:'social',level:2,word:'support',sentence:'Her family gave her strong ___.',zh:'她的家人给了她强大的支持。',hint:'支持'},
{id:'sc023',scene:'social',level:2,word:'message',sentence:'I sent her a quick ___ online.',zh:'我在网上给她发了一条简短的信息。',hint:'信息'},
{id:'sc024',scene:'social',level:2,word:'chat',sentence:'We had a friendly ___ after class.',zh:'下课后我们友好地聊了聊。',hint:'聊天'},
{id:'sc025',scene:'social',level:2,word:'relationship',sentence:'They have a healthy and honest ___.',zh:'他们有着健康而真诚的关系。',hint:'关系'},
{id:'sc026',scene:'social',level:3,word:'community',sentence:'The local ___ organized a charity event.',zh:'当地社区组织了一场慈善活动。',hint:'社区'},
{id:'sc027',scene:'social',level:3,word:'celebrate',sentence:'We will ___ her success together.',zh:'我们会一起庆祝她的成功。',hint:'庆祝'},
{id:'sc028',scene:'social',level:3,word:'compliment',sentence:'She gave me a nice ___ about my presentation.',zh:'她称赞了我的演讲。',hint:'称赞'},
{id:'sc029',scene:'social',level:3,word:'apologize',sentence:'You should ___ for being late.',zh:'你应该为迟到而道歉。',hint:'道歉'},
{id:'sc030',scene:'social',level:3,word:'gather',sentence:'Families usually ___ during festivals.',zh:'家庭通常会在节日期间聚会。',hint:'聚集'},
{id:'sc031',scene:'social',level:3,word:'discussion',sentence:'The ___ became very interesting.',zh:'讨论变得非常有趣。',hint:'讨论'},
{id:'sc032',scene:'social',level:3,word:'humor',sentence:'His sense of ___ made everyone laugh.',zh:'他的幽默感让大家都笑了。',hint:'幽默'},
{id:'sc033',scene:'social',level:3,word:'contact',sentence:'Please keep in ___ after graduation.',zh:'毕业后请保持联系。',hint:'联系'},
{id:'sc034',scene:'social',level:3,word:'cooperate',sentence:'Students must ___ on the project.',zh:'学生们必须合作完成这个项目。',hint:'合作'},
{id:'sc035',scene:'social',level:3,word:'trust',sentence:'A strong friendship needs mutual ___.',zh:'牢固的友谊需要彼此信任。',hint:'信任'},
{id:'sc036',scene:'social',level:4,word:'interaction',sentence:'Social ___ is important for mental health.',zh:'社交互动对心理健康很重要。',hint:'互动'},
{id:'sc037',scene:'social',level:4,word:'network',sentence:'She built a professional ___ online.',zh:'她在线上建立了职业人脉。',hint:'人脉网络'},
{id:'sc038',scene:'social',level:4,word:'recommend',sentence:'Can you ___ a good restaurant nearby?',zh:'你能推荐一家附近不错的餐厅吗？',hint:'推荐'},
{id:'sc039',scene:'social',level:4,word:'volunteer',sentence:'Many students ___ at community centers.',zh:'许多学生在社区中心做志愿者。',hint:'志愿者'},
{id:'sc040',scene:'social',level:4,word:'encourage',sentence:'Parents should ___ children to express themselves.',zh:'父母应该鼓励孩子表达自己。',hint:'鼓励'},
{id:'sc041',scene:'social',level:4,word:'confident',sentence:'She felt more ___ after making new friends.',zh:'交到新朋友后她变得更自信了。',hint:'自信的'},
{id:'sc042',scene:'social',level:4,word:'ceremony',sentence:'Many guests attended the wedding ___.',zh:'许多宾客参加了婚礼仪式。',hint:'仪式'},
{id:'sc043',scene:'social',level:4,word:'connection',sentence:'We formed a strong ___ through teamwork.',zh:'我们通过合作建立了牢固的联系。',hint:'联系'},
{id:'sc044',scene:'social',level:4,word:'generous',sentence:'He is always ___ with his time and help.',zh:'他总是慷慨地付出时间和帮助。',hint:'慷慨的'},
{id:'sc045',scene:'social',level:4,word:'greeting',sentence:'Her cheerful ___ brightened the room.',zh:'她愉快的问候让整个房间都充满活力。',hint:'问候'},
{id:'sc046',scene:'social',level:5,word:'communication',sentence:'Clear ___ can prevent misunderstandings.',zh:'清晰的沟通可以避免误会。',hint:'沟通'},
{id:'sc047',scene:'social',level:5,word:'collaboration',sentence:'The project succeeded through close ___.',zh:'这个项目通过紧密合作取得了成功。',hint:'合作'},
{id:'sc048',scene:'social',level:5,word:'hospitality',sentence:'The villagers showed great ___ to visitors.',zh:'村民们对游客表现出了极大的热情好客。',hint:'好客'},
{id:'sc049',scene:'social',level:5,word:'negotiation',sentence:'The business ___ lasted all afternoon.',zh:'商务谈判持续了一整个下午。',hint:'谈判'},
{id:'sc050',scene:'social',level:5,word:'sympathy',sentence:'She expressed deep ___ for his loss.',zh:'她对他的损失表达了深切同情。',hint:'同情'},
{id:'sc051',scene:'social',level:5,word:'persuade',sentence:'He tried to ___ his friends to join the club.',zh:'他试图说服朋友加入俱乐部。',hint:'说服'},
{id:'sc052',scene:'social',level:5,word:'relationship',sentence:'Healthy ___ require honesty and patience.',zh:'健康的人际关系需要诚实和耐心。',hint:'人际关系'},
{id:'sc053',scene:'social',level:5,word:'appreciate',sentence:'I really ___ your kindness and support.',zh:'我真的很感激你的善意和支持。',hint:'感激'},
{id:'sc054',scene:'social',level:5,word:'participate',sentence:'Everyone was encouraged to ___ in the event.',zh:'每个人都被鼓励参与这项活动。',hint:'参与'},
{id:'sc055',scene:'social',level:5,word:'understanding',sentence:'Mutual ___ helps friendships grow stronger.',zh:'相互理解能让友谊更加牢固。',hint:'理解'},
];
