// qbank/travel.js — 出行场景题库
export const QBANK_TRAVEL = [
{id:'tr006',scene:'travel',level:1,word:'ticket',sentence:'Please show your ___ before boarding.',zh:'登机前请出示你的票。',hint:'票'},
{id:'tr007',scene:'travel',level:1,word:'hotel',sentence:'We booked a ___ near the beach.',zh:'我们在海边预订了一家酒店。',hint:'酒店'},
{id:'tr009',scene:'travel',level:1,word:'train',sentence:'The ___ leaves at 8 a.m.',zh:'火车早上八点出发。',hint:'火车'},
{id:'tr010',scene:'travel',level:1,word:'map',sentence:'Use the ___ to find the museum.',zh:'用地图找到博物馆。',hint:'地图'},
{id:'tr011',scene:'travel',level:1,word:'bus',sentence:'We took a ___ to the city center.',zh:'我们乘公交车去了市中心。',hint:'公交车'},
{id:'tr012',scene:'travel',level:1,word:'flight',sentence:'Our ___ was delayed by two hours.',zh:'我们的航班延误了两个小时。',hint:'航班'},
{id:'tr013',scene:'travel',level:1,word:'taxi',sentence:'Let\'s call a ___ to the station.',zh:'我们叫辆出租车去车站吧。',hint:'出租车'},
{id:'tr014',scene:'travel',level:1,word:'guide',sentence:'The ___ showed us around the castle.',zh:'导游带我们参观了城堡。',hint:'导游'},
{id:'tr015',scene:'travel',level:1,word:'camera',sentence:'She packed her ___ for the trip.',zh:'她为旅行带上了相机。',hint:'相机'},
{id:'tr016',scene:'travel',level:2,word:'departure',sentence:'Check the ___ time before you leave.',zh:'出发前确认一下出发时间。',hint:'出发/离开'},
{id:'tr017',scene:'travel',level:2,word:'arrival',sentence:'The ___ time is listed on the screen.',zh:'到达时间显示在屏幕上。',hint:'到达'},
{id:'tr018',scene:'travel',level:2,word:'luggage',sentence:'Your ___ will arrive on belt 5.',zh:'你的行李会在5号传送带出来。',hint:'行李'},
{id:'tr019',scene:'travel',level:2,word:'boarding',sentence:'___ starts thirty minutes before takeoff.',zh:'登机在起飞前三十分钟开始。',hint:'登机'},
{id:'tr020',scene:'travel',level:2,word:'reservation',sentence:'I made a ___ for two nights.',zh:'我预订了两晚住宿。',hint:'预订'},
{id:'tr021',scene:'travel',level:2,word:'tourist',sentence:'Every ___ should carry a city map.',zh:'每位游客都应该带一张城市地图。',hint:'游客'},
{id:'tr022',scene:'travel',level:2,word:'subway',sentence:'The ___ is the fastest way downtown.',zh:'地铁是去市中心最快的方式。',hint:'地铁'},
{id:'tr023',scene:'travel',level:2,word:'platform',sentence:'Wait for the train on ___ 3.',zh:'请在3号站台等火车。',hint:'站台'},
{id:'tr024',scene:'travel',level:2,word:'schedule',sentence:'The bus ___ changed this weekend.',zh:'公交时刻表这个周末有变动。',hint:'时间表'},
{id:'tr025',scene:'travel',level:2,word:'souvenir',sentence:'She bought a ___ for her friend.',zh:'她给朋友买了一份纪念品。',hint:'纪念品'},
{id:'tr026',scene:'travel',level:3,word:'destination',sentence:'Paris is our final ___.',zh:'巴黎是我们的最终目的地。',hint:'目的地'},
{id:'tr027',scene:'travel',level:3,word:'customs',sentence:'We waited in line at ___.',zh:'我们在海关排队等候。',hint:'海关'},
{id:'tr028',scene:'travel',level:3,word:'itinerary',sentence:'Our ___ includes three countries.',zh:'我们的行程包括三个国家。',hint:'行程安排'},
{id:'tr029',scene:'travel',level:3,word:'terminal',sentence:'Meet me outside Terminal 2 at the airport.',zh:'在机场2号航站楼外见我。',hint:'航站楼'},
{id:'tr030',scene:'travel',level:3,word:'backpack',sentence:'He carried a heavy ___ during the hike.',zh:'徒步时他背着一个很重的背包。',hint:'背包'},
{id:'tr031',scene:'travel',level:3,word:'embassy',sentence:'Visit the ___ if you lose your passport.',zh:'如果丢了护照，请去大使馆。',hint:'大使馆'},
{id:'tr032',scene:'travel',level:3,word:'exchange',sentence:'Where can I ___ my money?',zh:'我可以在哪里兑换钱？',hint:'兑换'},
{id:'tr033',scene:'travel',level:3,word:'delay',sentence:'The storm caused a flight ___.',zh:'暴风雨导致航班延误。',hint:'延误'},
{id:'tr034',scene:'travel',level:3,word:'cruise',sentence:'They went on a luxury ___ last summer.',zh:'去年夏天他们参加了一次豪华游轮旅行。',hint:'游轮旅行'},
{id:'tr035',scene:'travel',level:3,word:'visa',sentence:'You need a ___ to enter the country.',zh:'进入这个国家需要签证。',hint:'签证'},
{id:'tr036',scene:'travel',level:4,word:'navigation',sentence:'The app provides voice ___ while driving.',zh:'这个应用在驾驶时提供语音导航。',hint:'导航'},
{id:'tr037',scene:'travel',level:4,word:'transfer',sentence:'We have a short ___ in Singapore.',zh:'我们在新加坡有一次短暂转机。',hint:'转机/换乘'},
{id:'tr038',scene:'travel',level:4,word:'excursion',sentence:'The hotel offers a mountain ___.',zh:'这家酒店提供山地短途旅行。',hint:'短途旅行'},
{id:'tr039',scene:'travel',level:4,word:'accommodation',sentence:'Finding cheap ___ during summer is difficult.',zh:'夏天很难找到便宜的住宿。',hint:'住宿'},
{id:'tr040',scene:'travel',level:4,word:'currency',sentence:'Always check the local ___ before traveling.',zh:'旅行前总要查看当地货币。',hint:'货币'},
{id:'tr041',scene:'travel',level:4,word:'adventure',sentence:'The jungle trip was a real ___.',zh:'丛林之旅真是一场冒险。',hint:'冒险'},
{id:'tr042',scene:'travel',level:4,word:'landmark',sentence:'The tower is a famous city ___.',zh:'这座塔是著名的城市地标。',hint:'地标'},
{id:'tr043',scene:'travel',level:4,word:'checkpoint',sentence:'Show your ID at the security ___.',zh:'请在安检处出示身份证件。',hint:'检查站'},
{id:'tr044',scene:'travel',level:4,word:'route',sentence:'This ___ avoids heavy traffic.',zh:'这条路线避开了严重堵车。',hint:'路线'},
{id:'tr045',scene:'travel',level:4,word:'journey',sentence:'The overnight ___ was comfortable.',zh:'这次过夜旅程很舒适。',hint:'旅程'},
{id:'tr046',scene:'travel',level:5,word:'transportation',sentence:'Public ___ is very convenient here.',zh:'这里的公共交通非常方便。',hint:'交通运输'},
{id:'tr047',scene:'travel',level:5,word:'immigration',sentence:'We spent an hour at ___.',zh:'我们在移民检查处待了一个小时。',hint:'移民检查'},
{id:'tr048',scene:'travel',level:5,word:'baggage',sentence:'Extra ___ may cost more money.',zh:'额外行李可能需要更多费用。',hint:'行李'},
{id:'tr049',scene:'travel',level:5,word:'sightseeing',sentence:'We went ___ around the old town.',zh:'我们在老城区观光。',hint:'观光'},
{id:'tr050',scene:'travel',level:5,word:'international',sentence:'This is an ___ airport.',zh:'这是一座国际机场。',hint:'国际的'},
{id:'tr051',scene:'travel',level:5,word:'expedition',sentence:'The scientists joined an Arctic ___.',zh:'科学家们参加了一次北极探险。',hint:'探险'},
{id:'tr052',scene:'travel',level:5,word:'receptionist',sentence:'Ask the ___ for local recommendations.',zh:'向前台接待员询问当地推荐。',hint:'接待员'},
{id:'tr053',scene:'travel',level:5,word:'cancellation',sentence:'The storm caused the ___ of many flights.',zh:'暴风雨导致许多航班取消。',hint:'取消'},
{id:'tr054',scene:'travel',level:5,word:'insurance',sentence:'Travel ___ can cover lost luggage.',zh:'旅行保险可以赔偿丢失的行李。',hint:'保险'},
{id:'tr055',scene:'travel',level:5,word:'layover',sentence:'We had a long ___ in Dubai.',zh:'我们在迪拜有很长时间的中途停留。',hint:'中途停留'},
];
