// qbank/work.js — 工作与职场场景 · Oxford 3000
// fix: qwk001-qwk005 重命名（原 wk001-wk005 与 quiz.js 内置题ID冲突）

export const QBANK_WORK = [
{id:'qwk001',scene:'work',level:1,word:'job',sentence:'She got a new ___ at the hospital.',zh:'她在医院找到了一份新工作。',hint:'工作（名词）'},
{id:'qwk002',scene:'work',level:1,word:'office',sentence:'He works in an ___ in the city centre.',zh:'他在市中心的一间办公室工作。',hint:'办公室'},
{id:'qwk003',scene:'work',level:1,word:'boss',sentence:'My ___ is very strict about deadlines.',zh:'我的老板对截止日期非常严格。',hint:'老板'},
{id:'qwk004',scene:'work',level:1,word:'meeting',sentence:'We have a team ___ every Monday morning.',zh:'我们每周一早上都有团队会议。',hint:'会议'},
{id:'qwk005',scene:'work',level:1,word:'salary',sentence:'He negotiated a higher ___ before accepting the offer.',zh:'他在接受邀约前谈判了更高的薪水。',hint:'薪水'},
{id:'wk006',scene:'work',level:1,word:'interview',sentence:'She prepared thoroughly for the job ___.',zh:'她为工作面试做了充分准备。',hint:'面试'},
{id:'wk007',scene:'work',level:1,word:'colleague',sentence:'My ___ helped me finish the report.',zh:'我的同事帮我完成了报告。',hint:'同事'},
{id:'wk008',scene:'work',level:1,word:'busy',sentence:"I'm too ___ to take a lunch break today.",zh:'我今天太忙了，没时间吃午饭。',hint:'忙碌的'},
{id:'wk009',scene:'work',level:1,word:'project',sentence:'The whole team worked on the ___ together.',zh:'整个团队一起参与了这个项目。',hint:'项目'},
{id:'wk010',scene:'work',level:1,word:'deadline',sentence:'The ___ for this report is Friday.',zh:'这份报告的截止日期是周五。',hint:'截止日期'},
{id:'wk011',scene:'work',level:2,word:'promote',sentence:'She was ___ to senior manager last year.',zh:'她去年晋升为高级经理。',hint:'晋升（过去分词）'},
{id:'wk012',scene:'work',level:2,word:'resign',sentence:'He decided to ___ after ten years at the company.',zh:'他决定在公司工作十年后辞职。',hint:'辞职（动词）'},
{id:'wk013',scene:'work',level:2,word:'overtime',sentence:'She worked ___ every night this week.',zh:'她这周每晚都加班。',hint:'加班'},
{id:'wk014',scene:'work',level:2,word:'remote',sentence:'He works ___ from home three days a week.',zh:'他每周有三天在家远程工作。',hint:'远程地（副词）'},
{id:'wk015',scene:'work',level:2,word:'teamwork',sentence:'Good ___ is essential in any organisation.',zh:'在任何组织中，团队合作都是必不可少的。',hint:'团队合作'},
{id:'wk016',scene:'work',level:2,word:'feedback',sentence:'She gave helpful ___ on his presentation.',zh:'她对他的演讲给出了有益的反馈。',hint:'反馈'},
{id:'wk017',scene:'work',level:2,word:'recruit',sentence:'The company plans to ___ fifty new staff.',zh:'公司计划招募五十名新员工。',hint:'招募（动词）'},
{id:'wk018',scene:'work',level:2,word:'appraisal',sentence:'Annual ___ reviews take place every December.',zh:'年度绩效评估在每年十二月进行。',hint:'绩效评估'},
{id:'wk019',scene:'work',level:2,word:'contract',sentence:'She signed a two-year ___ with the firm.',zh:'她与公司签了一份为期两年的合同。',hint:'合同'},
{id:'wk020',scene:'work',level:2,word:'benefit',sentence:'The job comes with great health ___.',zh:'这份工作附带很好的健康福利。',hint:'福利（复数）'},
{id:'wk021',scene:'work',level:3,word:'redundant',sentence:'Two hundred workers were made ___ last month.',zh:'上个月有两百名工人被裁员。',hint:'被裁员的/多余的'},
{id:'wk022',scene:'work',level:3,word:'delegation',sentence:'Effective ___ is a key leadership skill.',zh:'有效的授权是关键的领导技能。',hint:'授权/委派'},
{id:'wk023',scene:'work',level:3,word:'probation',sentence:'He is still on ___ for his first three months.',zh:'他仍在前三个月的试用期内。',hint:'试用期'},
{id:'wk024',scene:'work',level:3,word:'incentive',sentence:'Bonuses act as a financial ___ for staff.',zh:'奖金对员工起到经济激励的作用。',hint:'激励/刺激'},
{id:'wk025',scene:'work',level:3,word:'liability',sentence:'The company accepted full ___ for the accident.',zh:'公司承担了事故的全部责任。',hint:'责任/负债'},
{id:'wk026',scene:'work',level:3,word:'turnover',sentence:'High staff ___ is costly for any business.',zh:'高员工流动率对任何企业来说都代价高昂。',hint:'流动率/营业额'},
{id:'wk027',scene:'work',level:3,word:'grievance',sentence:'She filed a formal ___ against her manager.',zh:'她对她的经理提出了正式投诉。',hint:'投诉/不满'},
{id:'wk028',scene:'work',level:3,word:'hierarchy',sentence:'The company has a very flat ___.',zh:'这家公司的层级结构非常扁平。',hint:'等级制度'},
{id:'wk029',scene:'work',level:3,word:'collaborate',sentence:'The two teams ___ on the research project.',zh:'两个团队合作开展了这项研究项目。',hint:'合作（动词）'},
{id:'wk030',scene:'work',level:3,word:'productivity',sentence:'Working from home increased her ___ significantly.',zh:'在家工作显著提高了她的生产力。',hint:'生产力'},
{id:'wk031',scene:'work',level:4,word:'remuneration',sentence:'The ___ package includes a generous pension.',zh:'薪酬待遇包括丰厚的养老金。',hint:'薪酬/报酬'},
{id:'wk032',scene:'work',level:4,word:'arbitration',sentence:'The dispute went to ___ rather than court.',zh:'纠纷进行了仲裁而不是上法庭。',hint:'仲裁'},
{id:'wk033',scene:'work',level:4,word:'stakeholder',sentence:'All ___ were consulted before the decision.',zh:'在做出决定之前咨询了所有利益相关方。',hint:'利益相关者'},
{id:'wk034',scene:'work',level:4,word:'outsource',sentence:'The firm decided to ___ its IT support.',zh:'公司决定将IT支持外包。',hint:'外包（动词）'},
{id:'wk035',scene:'work',level:4,word:'benchmark',sentence:'Set a ___ to measure future performance.',zh:'设立基准来衡量未来的绩效。',hint:'基准/标杆'},
{id:'wk036',scene:'work',level:4,word:'bureaucracy',sentence:'The paperwork was slowed down by ___.',zh:'文件处理被官僚体制拖慢了。',hint:'官僚体制'},
{id:'wk037',scene:'work',level:4,word:'consolidate',sentence:'They plan to ___ the two departments into one.',zh:'他们计划将两个部门合并为一个。',hint:'合并/巩固（动词）'},
{id:'wk038',scene:'work',level:4,word:'autonomy',sentence:'Employees need ___ to do their best work.',zh:'员工需要自主权才能做出最好的工作。',hint:'自主权'},
{id:'wk039',scene:'work',level:4,word:'mandate',sentence:'The CEO has a clear ___ to cut costs.',zh:'CEO有明确的削减成本的授权。',hint:'授权/指令'},
{id:'wk040',scene:'work',level:4,word:'diligent',sentence:'She is ___ and never misses a deadline.',zh:'她勤勉尽责，从不错过截止日期。',hint:'勤勉的'},
{id:'wk041',scene:'work',level:5,word:'fiduciary',sentence:'Directors have a ___ duty to shareholders.',zh:'董事对股东负有受托责任。',hint:'受托的/信托的'},
{id:'wk042',scene:'work',level:5,word:'retrenchment',sentence:'The economic crisis led to mass ___.',zh:'经济危机导致了大规模裁员。',hint:'裁员/缩减'},
{id:'wk043',scene:'work',level:5,word:'nepotism',sentence:"Accusations of ___ damaged the company's reputation.",zh:'关于任人唯亲的指控损害了公司的声誉。',hint:'任人唯亲'},
{id:'wk044',scene:'work',level:5,word:'meritocracy',sentence:'A true ___ rewards skill over connections.',zh:'真正的精英制度奖励能力而非关系。',hint:'精英制度'},
{id:'wk045',scene:'work',level:5,word:'emolument',sentence:'His total ___ exceeded two million a year.',zh:'他的总报酬每年超过两百万。',hint:'报酬/薪俸（正式用语）'},
];
